### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by Tealons** [oracle/dotnet-db-samples#108]
We are using ODP.NET for connecting to a Oracle database. The code is something like this:

            connectionStringBuilder.DataSource = txtBx_sid.Text;
            connectionStringBuilder.UserID = txtBx_user.Text;
            connectionStringBuilder.Password = txtBx_pass.Text;

            var connectionOracleClient = new OracleConnection(connectionStringBuilder.ConnectionString);

            if (connectionOracleClient != null)
            {

                if (connectionOracleClient.State != ConnectionState.Open)
                {
                    try
                    {
                        connectionOracleClient.Open();
                        MessageBox.Show("Connection establised!");
                    }
                    catch (Exception exception)
                    {
                        MessageBox.Show($"ErrorMessage:{Environment.NewLine} {exception.Message} {Environment.NewLine}{Environment.NewLine} InnerException:{Environment.NewLine}{exception.InnerException} {Environment.NewLine}{Environment.NewLine} Stacktrace:{Environment.NewLine} {exception.StackTrace}");

                    }

                }

                connectionOracleClient.Close();
                MessageBox.Show("Connection Closed.");

The datasource is in this format: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=hostname)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=servicename)));

This works in our test environment and with several customers.

The problem is dat we get a connection timeout with one of our customers. We tested the server connection with powershell with the following command: Test-NetConnection -ComputerName "hostname" -Port 1521. And that works, so it's not a network problem.

We also tried connecting with the database via SQLPlus from another client and that also works. 

We also looked at the listener log, but don't see any log items of the client that we try to connect with. 

We have no idea how to proceed with debugging this issue. Can you help us with the next steps? One significant difference btw, is the fact that this customer runs the database in the Oracle Cloud. Our own test environment and other customers run their database on-premise. I'm not sure if that makes any difference?

We currently use Oracle.ManagedDataAccess version 19.9.0.

**Comment by alexkeh** [comment]
Are you using a TLS wallet with the connection? If so, problems with the wallet sometimes takes longer than the default 15 second connection timeout to materialize. The first thing I would do then is to increase the connection string Connection Timeout value to 120. You will then be able to see the actual error then.

You can also turn on ODP.NET tracing. In ODP.NET Core, you can add  something like these two lines when it starts up prior to opening the first connection. 

OracleConfiguration.TraceFileLocation = @"D:\traces";
OracleConfiguration.TraceLevel = 7;

Since I don't see a TnsAdmin nor WalletLocation set, check to make sure the wallet and *.ora files are being picked up by ODP.NET for the correct location. The trace will tell you the location if these files were picked up.

**Comment by Tealons** [comment]
Thanks. Our current application is a WPF application on .NET 4.6.1. I will write a test application that runs on .NET Core. Also, the connection timeout is readonly, you can override it with the connectionstring I assume?

I will let you know what the tracing file gives after I created the .NET Core application.

**Comment by alexkeh** [comment]
Sorry, I assumed you were using ODP.NET Core. The trace setting code also works with managed ODP.NET assuming you are using one of the newer versions. If not, you can always enable tracing via the .NET config file.

Yes, the connection timeout is writeable in the connection string.

**Comment by alexkeh** [comment]
The lack of response error is indicative that something is swallowing the message on the way out (or possibly in). Did you try your PowerShell connection test from the same machine the ODP.NET client is running from? If Powershell is not working, that would be indicative of a firewall, such as from a corporate intranet, that is blocking the communication.

TLS is more typical for those using Oracle Autonomous Database, but it's not what you are using it appears.

**Comment by Tealons** [comment]
Yes, we tested via powershell on the same machine. I'm not that familiar with the Oracle Cloud, but my customer is hosting a 12.1 database there. Is there any ip firewall restriction possible with an Oracle database?

One strategy I'm now considering is letting the customer install SQL Developer on the same machine ODP.NET is running on and to test if the IDE can make the connection work. If not, some firewall in the network is blocking, otherwise the problem is in ODP.NET. However, I assume the protocol that ODP.NET and SQL Developer is the same?

**Comment by alexkeh** [comment]
I'll have to ask my dev team if they've seen this issue. 

One can restrict network access to an Oracle cloud DB instance. The fact another machine can reach the DB instance can mean either such a firewall permits this access or at least that particular machine's IP is greenlisted for DBCS access. If Powershell can reach the DB machine, then ODP.NET should be able to reach the machine as well.

Yes, running SQL Developer on the same machine would verify whether DB access works from that machine since Powershell is just verifying machine access. However, the protocol ODP.NET and SQL Developer use are different. SQL Developer generally uses thin JDBC and managed ODP.NET uses a similar Oracle native protocol implemented in C# instead of Java.

**Comment by alexkeh** [comment]
Hi @Tealons 
One of our developers reviewed your trace. Here's his comments below. He would also like to see the rest of your trace. If it's too long or if you don't want to post it on this forum, you can send it via email to dotnet_us(at)oracle.com.
=====

In general, he tried to connect on some redacted hostname, that resolved to multiple IPs. The connect appears to have failed on the first IP (10.129.168.102), for an unknown reason since the trace was chopped. He then went on to try to connect on OTHER IPs from the resolved list (maybe...maybe only 2 IPs), and finally failed w/ a timeout on 10.129.168.100, which appears to be the LAST IP.

My *guess* is that they expect to connect on one of those INITIAL IPs (eg, 10.129.168.102), and are failing with a timeout on the later IPs, because those later hosts are not really fully setup.

**Comment by Tealons** [comment]
Hi @alexkeh, 
I have just send you the tracefile. I hope this helps. I also asked our customer to install SQL Developer. I will report back when this is done and we tested the connection.

**Comment by alexkeh** [comment]
@Tealons 
Got the file. We'll let you know what we find.

**Comment by alexkeh** [comment]
After further discussion with the DB team, this appears to have been an issue with the RAC setup itself, not an ODP.NET issue. Closing the issue.
