### ISSUE TITLE
Oracle.DataAccess.dll ODP.NET vs Nuget package -- Trying to connect to Oracle 19

### ISSUE THREAD

**Issue by s3YwCf2ZbfJG4SHAfjQMAjtsf** [oracle/dotnet-db-samples#118]
I hope this is ok to post here, it isn't about the Managed Data Access libraries

Oracle DataAccess DLL version information:

https://www.nuget.org/packages/Oracle.DataAccess.x86.4/
DLL version 4.112.3.0 

Oracle 12 Client (32-bit) ODP.NET folder
DLL Version 4.122.1.0

Oracle 19 client (32-bit)  ODP.NET folder
DLL Version 4.122.19.1

We have been upgrading x86 C# web application to .Net 4.8 and Oracle 19, that was previously using the nuget version of the Oracle DataAccess. The last update to the nuget package is May 2016 and of course doesn't work with Oracle 19.    It appears as though we should use the ODP.NET Oracle 19 version.   However, we are getting an error trying to make connections and build connection strings:

An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

   at Oracle.DataAccess.Client.OpsInit.CheckVersionCompatibility(String version)
   at Oracle.DataAccess.Client.OracleInit.Initialize()
   at Oracle.DataAccess.Client.OracleConnectionStringBuilder..cctor()

The type initializer for 'Oracle.DataAccess.Client.OracleConnectionStringBuilder' threw an exception.

I am not sure why the error is happening.   It is rendering in 32 bit IIS express (development wise) and everything seems to fine until we get the OracleConnectionStringBuilder as in above.

I see the version numbering is different between the ODP.NET and Nuget versions of the Oracle.DataAccess, not sure if it is suggesting that there are different rules with the ODP.NET version. 

****************

On another note, I tried the Oracle.ManagedDataAccess nuget library, The Connections and ConnectionStrings work fine, but we are using UDTs extensively to pass to oracle table parameters in procedures.

**Comment by alexkeh** [comment]
Unmanaged ODP.NET contains the Oracle Client, which can be 32-bit or 64-bit. On the machine you are running from, you likely have 64-bit Oracle Client installed, instead of 32-bit client.

If you do have the 32-bit client installed, then ODP.NET must be finding the 64-bit Oracle Client DLLs first in the DllPath and/or Windows Path.

Be sure to set the DllPath setting in your .NET config file based on where ODP.NET should find its ORACLE_BASE\\ORACLE_HOME\bin directory. That's how unmanaged ODP.NET should find its dependent unmanaged DLLs.

Numbering for ODP.NET NuGet packages only applies to the NuGet package installs only, not the ODP.NET component version. NuGet version has its own requirements, such as three sets of digits only and dependency logic built around package versions, which don't work that well with Oracle's existing versioning scheme.

**Comment by s3YwCf2ZbfJG4SHAfjQMAjtsf** [comment]
Thanks, apparently, I did have the 64 bit client installed.
