### ISSUE TITLE
Timeout using v2.19.100

### ISSUE THREAD

**Issue by sierrodc** [oracle/dotnet-db-samples#134]
We are (still) working with Oracle 11g.
We have no issue using nuget 2.19.91 and lower. With the new version the following simple code fails:

```
using (var conn = new Oracle.ManagedDataAccess.Client.OracleConnection("Data Source=xxx;User Id=xxx;Password=xxx;"))
{
     conn.Open();
}
```
with the Timeout exception. You can find details in the attached trace.txt file.

[trace.txt](https://github.com/oracle/dotnet-db-samples/files/5747568/trace.txt)

**Comment by alexkeh** [comment]
Increase the Connection Timeout in the ODP.NET connection string to let the error source manifest itself. Your issue is likely taking much longer to manifest itself than the 15 second timeout default.

**Comment by sierrodc** [comment]
Hi,

 I've tried setting Connection Timeout to 300 with the same result. Here is the trace.
[trace.txt](https://github.com/oracle/dotnet-db-samples/files/5747971/trace.txt)

**Comment by alexkeh** [comment]
Yes, I see the new trace is still timing out. Unfortunately, the trace doesn't indicate what the problem source is. My expectation is that the DB server would indicate why it's not granting a connection to the app. Instead, it's just letting the timeout occur.

I would ask my DBA to see what's happening on the DB server side when ODP.NET tries to connect.

What has changed between your last successful ODP.NET Core run to this DB and your upgrade? I see you are using .NET 5.0.1. Presumably, you were using ODP.NET Core 2.19.91 with .NET Core 3.1 or lower. Were there any other changes?

**Comment by sierrodc** [comment]
Unfortunately nothing. And if I change back the package version to 2.19.91, I'm able to connect to exadata. Here is the log.
[trace_2.19.91.txt](https://github.com/oracle/dotnet-db-samples/files/5749956/trace_2.19.91.txt)

As you can see, after retrieving the tnsnames.ora (and listing all the available connections), the first thing it does is to try to connect to server using TcpTransportAdapter.Connect(). This doesn't happen with 2.19.100 I don't know why (is closed source manageddataaccess, isn't it? I suppose I cannot debug step-by-step).

**Comment by alexkeh** [comment]
I took a look at the recent bugs filed that match your symptoms and your setup. I found one that matches closely, bug 32299349. It occurs when failover is turned on in the connect descriptor, such as "(FAILOVER=YES)" which you have. ODP.NET will then hit a connection timeout even if the timeout value is very high.

To validate it's the same bug, can you remove the FAILOVER setting from your connect descriptor? If you can connect, then it's extremely likely you are encountering this bug. The fix is scheduled to be released in early January on NuGet Gallery.

**Comment by sierrodc** [comment]
Hi,

 you are right. If I remove completely the (FAILOVER=YES) settings I'm able to connect, no more timeout exceptions. If I set (FAILOVER=NO), the timeout exception is still raised.
So, according to your last message, this fix will be released soon, am I right?

Thanks a lot.

**Comment by sungam3r** [comment]
Relates to #126

**Comment by sungam3r** [comment]
@alexkeh I was able to reproduce the problem.

Connection string:
```
Data Source=(DESCRIPTION=(ENABLE=BROKEN)(LOAD_BALANCE=off)(FAILOVER=on)(TRANSPORT_CONNECT_TIMEOUT=10)
(ADDRESS=(PROTOCOL=tcp)(HOST=tst-srv1)(PORT=1526))(ADDRESS=(PROTOCOL=tcp)(HOST=tst-srv2)(PORT=1525))
(CONNECT_DATA=(SERVICE_NAME=someservice)(FAILOVER_MODE=(TYPE=session)(METHOD=basic))));
User Id=test_user;Password=test_password
```

There is no service with name `someservice` on port 1526 intentionally to reproduce the issue. It is on the 1525 port. Our assumption was that the correctness of the connection string depends on the order of the addresses. In practice, it turned out that this does not depend on the order of addresses.

Results:

| version | first port 1526 | first port 1525 |
|--|--|--|
| 2.19.80 | OK | OK |
| 2.19.91 | OK | OK |
| 2.19.100 | Timeout after 15 seconds | Timeout after 15 seconds |  

After setting additional timeout `(CONNECTION_TIMEOUT=180)`:
```
Data Source=(DESCRIPTION=(ENABLE=BROKEN)(LOAD_BALANCE=off)(FAILOVER=on)(CONNECTION_TIMEOUT=180)
(TRANSPORT_CONNECT_TIMEOUT=10)(ADDRESS=(PROTOCOL=tcp)(HOST=tst-srv1)(PORT=1526))
(ADDRESS=(PROTOCOL=tcp)(HOST=tst-srv2)(PORT=1525))(CONNECT_DATA=(SERVICE_NAME=someservice)
(FAILOVER_MODE=(TYPE=session)(METHOD=basic))));User Id=test_user;Password=test_password
```

Results:

| version | first port 1526 | first port 1525 |
|--|--|--|
| 2.19.80 | OK | OK |
| 2.19.91 | OK | OK |
| 2.19.100 | Timeout after 15 seconds | Timeout after 15 seconds |

> The fix is scheduled to be released in early January on NuGet Gallery.

Really looking forward to it.

**Comment by alexkeh** [comment]
@sierrodc Yes, soon. The fix is planned to be delivered in early January.

**Comment by alexkeh** [comment]
[Managed ODP.NET 19.10.1](https://www.nuget.org/packages/Oracle.ManagedDataAccess/19.10.1) and [ODP.NET Core 2.19.100](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/2.19.100) are now available on NuGet Gallery. They both have a fix for Bug 32299349.

**Comment by sungam3r** [comment]
2.19.101 I think

**Comment by sungam3r** [comment]
I checked v2.19.101, it works.

**Comment by sierrodc** [comment]
I can confirm. Thanks.
