### ISSUE TITLE
Maximum number of expressions in a list is 1000

### ISSUE THREAD

**Issue by Aleksaas** [oracle/dotnet-db-samples#141]
I get this error message when using `Contains` in queries with a long list of parameters: 
`ORA-01795: maximum number of expressions in a list is 1000`.
Working with Oracle 11. Is this a bug? And is there any workaround to fix this?

**Comment by alexkeh** [comment]
It's not a bug from the standpoint that 1000 items is the Oracle DB limit for an IN clause. I'm making an assumption that's the clause that the error is originating from since it's a common one. The workaround is to break the IN clause up into multiple IN clauses with an OR expression. Of course, if this is LINQ, it's something you may not have direct control over.

Can you provide a simple test case for us to review? The Oracle .NET team can take a look to see if we can resolve the issue from a provider level.

**Comment by Aleksaas** [comment]
I have a query like this `_ctx.InterruptEeoLinks.Where(e => relevantNodeIds.Contains(e.ParentEeoId)).ToList()`. You can query any table, it is just important that list of ids exceeds max number of params allowed. In my case `relevantNodeIds` had between 500 and 1000 elements, so not sure where the limit is. I also found that devart had the same bug and they solved it. Not sure if I can post here link to their forum but this is topic where they explained their fix: https://forums.devart.com/viewtopic.php?t=39921.

**Comment by alexkeh** [comment]
I was able to reproduce the issue myself. I opened bug 32430968 to track this issue internally at Oracle and have the dev team review. Thanks for reporting.

**Comment by alexkeh** [comment]
This bug has been fixed and will be delivered in the next Oracle EF Core release.

**Comment by oberreiterm** [comment]
Hi, any timeline on when we could expect this bug fix to be released? Thanks.

**Comment by alexkeh** [comment]
The Oracle EF Core 19.11 packages should be up on NuGet Gallery this month. The ODP.NET 19.11 packages already got uploaded.

The next Oracle EF Core 5 package will probably occur later on since that was just released last month and it's based on 21c.
