### ISSUE TITLE
Microsoft.EntityFrameworkCore.Database.Command 查询速度 一分钟，同样sql sql工具里面只需要 1s

### ISSUE THREAD

**Issue by fanhai** [oracle/dotnet-db-samples#142]
Category: Microsoft.EntityFrameworkCore.Database.Command
EventId: 20100

Executing DbCommand [Parameters=[:stime_0='?' (DbType = DateTime), :etime_1='?' (DbType = DateTime), :p_2='?' (DbType = Int32), :p_3='?' (DbType = Int32)], CommandType='Text', CommandTimeout='0']
Select 
 K0 "ID", K1 "ACTION_NAME", K2 "ALARM_TRANS_ID", K3 "COMPARE_TYPE", K4 "CREATED_TIME", K5 "CREATOR", K6 "EQP_NO", K7 "LOT_ID", K8 "REALLYVALUE", K9 "REMARKS", K10 "SET_TIME", K11 "UPDATED_TIME", K12 "UPDATOR" from(
select "m2".*, rownum r2 from
(
SELECT "s"."ID" K0, "s"."ACTION_NAME" K1, "s"."ALARM_TRANS_ID" K2, "s"."COMPARE_TYPE" K3, "s"."CREATED_TIME" K4, "s"."CREATOR" K5, "s"."EQP_NO" K6, "s"."LOT_ID" K7, "s"."REALLYVALUE" K8, "s"."REMARKS" K9, "s"."SET_TIME" K10, "s"."UPDATED_TIME" K11, "s"."UPDATOR" K12
FROM "LION_ALM_ACTION_HISTORY" "s"
WHERE ((("s"."CREATED_TIME" >= :stime_0)) AND (("s"."CREATED_TIME" < :etime_1)))
) "m2"
) "m1"
where r2 > :p_2
and r2 <= (:p_2 + :p_3)

**Comment by alexkeh** [comment]
The most common reason I've seen for EF Core query performance issues is from performing full table scans and data type conversions. The problem is described here:

https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/EFCorePerformanceConsiderations.html#GUID-E12B036C-A8B7-4891-9713-B079AC4815DD

The resolution for this particular problem is to ensure you supply the correct EF Core model metadata so that the DB does not need to conduct data type conversions and can use a more efficient execution plan.

**Comment by fanhai** [comment]
根据指引解决了问题，非常感谢
