### ISSUE TITLE
EF Core5: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by stefannikolei** [oracle/dotnet-db-samples#163]
I am using EF Core 5 with the following configuration:

```
            services.AddDbContextPool<OracleDbContext>(options =>
            {
                options.UseOracle(configuration.GetConnectionString("connectionStringOracle"),
                    x =>
                    {
                        x.MigrationsHistoryTable("MIGRATIONHISTORYCORE", "MyApp");
                        x.MigrationsAssembly("MyAppDataAccess.Core");
                    });
            });
```

Yesterday i got many of this exceptions:

```

Index was outside the bounds of the array.
OracleInternal.ConnectionPool.PoolManager`3 in CreateNewPR
OracleInternal.ConnectionPool.OraclePoolManager in CreateNewPR
OracleInternal.ConnectionPool.PoolManager`3 in Get
OracleInternal.ConnectionPool.OraclePoolManager in Get
OracleInternal.ConnectionPool.OracleConnectionDispenser`3 in Get
Oracle.ManagedDataAccess.Client.OracleConnection in Open
System.Data.Common.DbConnection in OpenAsync
Microsoft.EntityFrameworkCore.Storage.RelationalConnection+<OpenInternalAsync>d__58 in OpenInternalAsync
Microsoft.EntityFrameworkCore.Storage.RelationalConnection+<OpenInternalAsync>d__58 in OpenInternalAsync
Microsoft.EntityFrameworkCore.Storage.RelationalConnection+<OpenAsync>d__54 in OpenAsync
Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory+OracleRelationalCommandBuilder+OracleRelationalCommand+<ExecuteReaderAsync>d__9 in ExecuteReaderAsync
Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1+AsyncEnumerator+<InitializeReaderAsync>d__15 in InitializeReaderAsync
Oracle.EntityFrameworkCore.Storage.Internal.OracleExecutionStrategy+<ExecuteAsync>d__8`2 in ExecuteAsync
Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1+AsyncEnumerator+<MoveNextAsync>d__14 in MoveNextAsync
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1 in ToListAsync
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+<ToListAsync>d__65`1 in ToListAsync

```

The Exception did not fire all the time, but very often. It seemed like 1/3 requests were failing. 

Everything was working fine after restarting the application.

I also made a Dump for further investigations

@alexkeh

**Comment by alexkeh** [comment]
Can you reproduce the error consistently? Understanding the conditions the error occurs in is helpful to finding the root cause.

Can you share the ODP.NET trace when you can reproduce it?

It looks like your issue happens on the connection open call. A lot happens when Open() occurs, which makes it hard to diagnose just based on the error message and stack trace.

**Comment by stefannikolei** [comment]
It occurred only yesterday and not for every connection. But I got that error over a time frame of 6 hours. Only a restart of the app pool helped 

I can not reproduce is, neither can further look into it because there are no published symbols or source links :( 

But if it helps I have an memory dump of the application.

**Comment by alexkeh** [comment]
I'm not sure a memory dump would be that helpful in the case of intermittent connection errors. Traces are more helpful because they show the series of events before the error, at what point in the connection process the error occurred, and the complete error information.

**Comment by stefannikolei** [comment]
@alexkeh Ok. I will then try to make a trace when this happens again. Just that a Memory Dump could be helpful because we are using pooled DBContexts

The strange thing was, that some connections seemed to work and some did not..

**Comment by stefannikolei** [comment]
@alexkeh i got that error again. Could not collect a trace. Do you want me to just use dotnet-trace or what do you prefer to capture it?

**Comment by alexkeh** [comment]
If you can predict approximately when the problem occurs, enable [ODP.NET dynamic tracing](https://medium.com/oracledevs/odp-net-tracing-lets-get-dynamic-84183cf0629d) to collect the trace. That way, you don't need to have tracing on all the time.

The ODP.NET trace is what we need since you suspect it's a problem with the provider. 

Does this reproduce in a test environment? If so, you can just leave tracing on. When the problem occurs, you'll have the trace. In most cases, we will only need the first part of the trace (with all initial configuration info) and last part of the trace (with the specific call that failed and the series of events that led to it).

**Comment by stefannikolei** [comment]
Hm. This will get interesting... I haven't seen this behaviour in our Test environment. 

I saw the problem twice in Production. After an recycle of the App Pool some connections just failed with the Stacktrace posted above (It's always the same).

Doing another recycle fixes the problem. Because of that it will be probably hard to get the trace from the moment where it all started.

I will see what i can get when the problem occurs the next time...
