### ISSUE TITLE
Update request for Oracle.EntityFrameworkCore nuget package

### ISSUE THREAD

**Issue by MaherJendoubi** [oracle/dotnet-db-samples#170]
![image](https://user-images.githubusercontent.com/1798510/118185561-f9633d00-b43c-11eb-95b0-b449d78db8fe.png)

**Comment by alexkeh** [comment]
There's no 21c version for EF Core 5, which is why you don't see a 19c version of it updated a month ago. In general, we provide a new update once every three months for the most recent major Oracle releases. If there hasn't been any bug updates nor new features in those three months, we'll skip that quarter and deliver a new update the following quarter.

**Comment by MaherJendoubi** [comment]
Thank you Alex.
