### ISSUE TITLE
Oracle.EntityFrameworkCore US7ASCII Chinese query garbled code

### ISSUE THREAD

**Issue by GaoXiong666** [oracle/dotnet-db-samples#185]
Oracle.EntityFrameworkCore5.21.1,Database encoding format is 'SIMPLIFIED CHINESE_CHINA.US7ASCII',The Chinese data queried in .net5 is garbled

`services.AddDbContext<FinanceContext>(op =>  
            {  
                op.UseOracle(Configuration.GetConnectionString("Finance")  
                    , b => b.UseOracleSQLCompatibility("11")  
                    );  
            });  
`

I put the local environment variable 'NLS_ LANG 'is changed to the same. The query with' PL / SQL 'is normal, but the Chinese data in. Net5 is garbled

**Comment by alexkeh** [comment]
I haven't seen this problem before nor is there an existing bug with the same symptoms. I have a few questions.

Do you have a test case that my team can look at? That would make diagnosis and fixing the problem easier. 

What DB version are you using? It looks like it's DB 11.2.

Have you observed this problem in any other Oracle EF Core version?

**Comment by GaoXiong666** [comment]
This is my database version，11.2
![RL09VTBRKG(1YORQNBB2$O](https://user-images.githubusercontent.com/53500372/128273969-12650e31-d9ed-4644-80c6-edcf63d555b2.png)

This is the encoding format of my database
![image](https://user-images.githubusercontent.com/53500372/128278003-89c1b8e5-400e-406e-85eb-882f8a54b116.png)

This is Windows10 'NLS_ LANG' environment variable
![image](https://user-images.githubusercontent.com/53500372/128277873-c842a4ae-5c2f-49d6-a48a-ad2ce9181ea6.png)

This is the character set used by the 'PL / SQL' current session
![image](https://user-images.githubusercontent.com/53500372/128278052-6c50ac25-6a94-4ec6-bcce-98f678aaaa75.png)

Then create a table with 'PL / SQL' and one of the fields is VARCHAR2, 
Add Chinese data in VARCHAR2 field, such as '管理员',
![image](https://user-images.githubusercontent.com/53500372/128279222-6dd3a3ec-5927-4714-85d4-fbfe84987ee9.png)

Then create a new .Net5 web api project and reference Oracle.EntityFrameworkCore 5.21.1 nuget package
![image](https://user-images.githubusercontent.com/53500372/128279172-8cd7ff0f-be2c-45ad-adc4-bde2955fde6a.png)
![image](https://user-images.githubusercontent.com/53500372/128279138-a4a71137-bd81-4604-8fe4-171979812c2e.png)

As shown in the figure, Chinese data becomes garbled,
For historical reasons, we cannot change the encoding format of the database
This problem has appeared in the .Net Framework version,
The solution is to change Oracle.ManagedDataAccess.dll to Devart.Data.Oracle.dll，But that's for a fee, 
I searched other solutions and found using System.Data.OleDb is OK
![image](https://user-images.githubusercontent.com/53500372/128281154-a4a7b8aa-92e0-4a29-923f-52de2b5e4e44.png)

But they all need to be encapsulated into ORM to be suitable for promotion in our company's projects，
It's hard for me to do it alone，
This is the first time I use Oracle EF Core. I haven't used any other version ,
Can Oracle EF core solve this problem?

**Comment by alexkeh** [comment]
This may be an ODP.NET NLS issue, not a problem with Oracle EF Core. We'll take a look.

If you use modify your OLE DB .NET app to use ODP.NET, my guess is that you would see the same bug.

**Comment by alexkeh** [comment]
Thanks for reporting the issue!

We were able to reproduce the behavior. We have filed bug 33199181 to have the NLS team review it.

**Comment by swolicki** [comment]
.Net, like Java, internally works in Unicode UTF-16. Therefore, when data is read from the Oracle Database, it is automatically converted from the database character set to UTF-16. Conversion in the opposite direction happens on writes. This is not configurable. As your database character set declaration is US7ASCII, the .Net/RDBMS conversion happens from/to US7ASCII. The process cannot interpret Chinese codes. If the character codes are really from the ZHS16GBK, the leading byte of each Chinese character is >127, which means it has no interpretation in US7ASCII and is converted to the Unicode replacement character U+FFFD, which you see as the question mark in the diamond shape.

There is no good way to solve the problem other than repairing the database character set. You would have exactly the same issue with any Java program using JDBC (whether Thin or OCI-based).

**Comment by alexkeh** [comment]
Based on further analysis by the Oracle NLS team, this behavior is not a bug. I'll keep this issue open for a few days in case there are any comments.

**Comment by l2999019** [comment]
Is this problem finally solved? I had the same problem @GaoXiong666

**Comment by swolicki** [comment]
Repeating myself:
"There is no good way to solve the problem other than repairing the database character set. You would have exactly the same issue with any Java program using JDBC (whether Thin or OCI-based)."

Your database must use a character set that supports Chinese.

**Comment by GaoXiong666** [comment]
> Is this problem finally solved? I had the same problem @GaoXiong666

If it is a new project, you can use “freesql”.

**Comment by l2999019** [comment]
@GaoXiong666  freesql Can you solve the problem of garbled code? Are there any examples for reference?  3Q

**Comment by GaoXiong666** [comment]
> @GaoXiong666 freesql Can you solve the problem of garbled code? Are there any examples for reference? 3Q

I'm on vacation now. Here's the document：https://freesql.net/guide/freesql-provider-oracle.html

**Comment by 2881099** [comment]
> @GaoXiong666 freesql Can you solve the problem of garbled code? Are there any examples for reference? 3Q

dotnet add package FreeSql.Provider.OracleOledb

`
public class DB
{
    static Lazy<IFreeSql> oracleLazy = new Lazy<IFreeSql>(() => new FreeSql.FreeSqlBuilder()
        .UseConnectionString(FreeSql.DataType.Oracle, "Provider=OraOLEDB.Oracle;user id=9user;password=123456;data source=//127.0.0.1:1521/XE;Pooling=true;Max Pool Size=2")
        .UseAutoSyncStructure(true)
        .UseNameConvert(FreeSql.Internal.NameConvertType.ToUpper)
        .UseNoneCommandParameter(true)
        .UseMonitorCommand(cmd => Trace.WriteLine(cmd.CommandText))
        .Build());
    public static IFreeSql oracle => oracleLazy.Value;
}
`

https://github.com/dotnetcore/FreeSql/wiki

**Comment by John0King** [comment]
@alexkeh   May I ask what's the solution here ,  I'm using dapper  and the  ODP.net managed drive return garbled character，  Is there any settings I can put in my program to fix that  ?

**Comment by alexkeh** [comment]
@John0King The solution is to use a multibyte character set on the client side.

**Comment by John0King** [comment]
@alexkeh   but why JDBC, OLEDB do not have those issue ?    asking for 3rd party to change the charactor on their server is not possible.

> The solution is to use a multibyte character set on the client side.

client side ?     the server is using  `SIMPLIFIED CHINESE_CHINA.US7ASCII` ,  how do I change the encoding ?

**Comment by swolicki** [comment]
JDBC has exactly the same "issue". OLEDB may not have it (I do not remember) because it supports the ANSI mode. I put "issue" into quotes because the problem translates to "I cannot cheat anymore with ODP Net". The database is configured with a character set whose name says "United States 7-bit ASCII" and you complain that you cannot process Chinese 16-bit GBK data. Why do you complain? You could process it in an OCI or OLEDB application? Pure luck. Have you tried the UPPER SQL function on the data? Have you got your full-width Latin or Cyrillic letters uppercased? I guess not. Or SUBSTR? Has it correctly maintained the integrity of two-byte character codes with arbitrary offsets and lengths? I guess not. Chinese can be stored legally in an US7ASCII database either in NVARCHAR2/NCHAR columns or in RAW columns. In the first case, the character set is AL16UTF16 or UTF8, both being Unicode encodings supporting Chinese. In the second case, your data is not interpreted by the database and you can store whatever you want. Of course, we do not recommend these two approaches. The recommended approach is to use a database character set supporting Chinese: AL32UTF8 (preferred) or ZHS16GBK.

**Comment by John0King** [comment]
I know the issue,  but  this db is alreay support a large application running almost 7 years ,  and we as the 3rd party to the db owner who can not ask them to change the character  set  , because it have risk for their main application.    

> JDBC has exactly the same "issue"

I'm actully tried with the `upper` `lower` and `subStr`  ,  in PLSql ,  the `upper` and `lower` function is normll for Chinese character with `VarChar(50)`  type ,    and `subStr`  is count on 1 byte so  a Chinese charactor need use `2` length.  but `subStr` is barely used anywhere in both the Main application and 3rd party app as us.

I'm asking  a solution for this case (maybe via a  incorrect configuration for this  incorrect database), so we can use the `Oracle.MangedDataAccesss` and the `Oracle.MangedDataAccesss.Entity`  instead of  goes to the  deprated  `System.Data.Oracle` or the `oledb` .

**Comment by l2999019** [comment]
@alexkeh
How do I use character sets on the client side? Can you provide sample code? Thank you

**Comment by swolicki** [comment]
You cannot set the client character set in ODP .Net or JDBC. .Net/C# and Java are natively UTF-16 environments. Hence, the client character set is preset to UTF-16 and not configurable.

You do not have much choice here. Either change the client framework to one allowing cheating, use the NCHAR data types, or convert data between VARCHAR2 and RAW on the server (UTL_RAW/UTL_I18N) and back on the client. RAW does not undergo character set conversion of any kind.

By UPPER not working, I meant uppercasing of full-width Latin characters, such as U+FF41 (ａ), which should become U+FF21 (Ａ). GBK codes are, correspondingly, 0xA3E1 and 0xA3C1.

**Comment by John0King** [comment]
>  You cannot set the client character set in ODP .Net or JDBC.

there is data import export tool named `Pentaho Data Integration` ,  and  I using it's `Table Import` with `Oracle + JDBC(Native)`  and there are no garbled code for chinese characters, why is that happend ?

> .Net/C# and Java are natively UTF-16 environments

that's true,  but that is for the CLR  not for the user code.  there no native encoding in  dotnet's type system, it's either `string` or `byte[]` ,   and to decode the `byte[]`  into `string`, then you need to use `Encoding` class (like `Encoding.Utf8`, `Encoding.Unicode` or `Encoding.GetEncoding("GB2312")` ) .  I don't know much in the `Oracle.ManagedDataAccess`,  in my knowledge,  the drive is using `byte[]` to communicate with the db server,  and hence ,  we can convert  back to string when we found it correct encoding.

I'm wonder  why  OLEDB/ODBC/(or maybe JDBC) can process the encoding correctly and the managed drive can not ?

**Comment by alexkeh** [comment]
ODP.NET is not open source. 

In the ORM, are the data types for these columns identified as NVARCHAR2/NCHAR?
Is the problem being reported just for ODP.NET Core or does this affect managed ODP.NET? The OP was reporting for ODP.NET Core since they are using EF Core. Dapper can be run with .NET Core (ODP.NET Core) or .NET Framework (managed ODP.NET).

Does this problem occur in a non-ORM environment?

**Comment by John0King** [comment]
> In the ORM, are the data types for these columns identified as NVARCHAR2/NCHAR?

no,  I'm not pro dev on Oracle,  what I find is that PLSql's auto compete shows it's a `varchar(50)` type

> Is the problem being reported just for ODP.NET Core or does this affect managed ODP.NET? 

I'm current in a project  running on .net framework , so  I'm  on managed ODP.NET (not core) ,   but the core version should have same problem (this issue 185 is reporting it)

> Does this problem occur in a non-ORM environment?

Yes,  I'm current doing test  with `OracleConnection` with dapper,  so  I think the issue is hapened in the underling driver.


---------------------------
and I have a guess on this issue,   for OLEDB/ODBC / PLSql ,  it is using  the windows local encoding  for `varchar` type  (or country/region base encoding detect    or simply use `utf16`)  and ignored the db's character set setting.   and plus the TNS_Lang  is setting to the same value between client and server.   so  the native driver (c/c++)  simply  push the binary of text to the db and the client decode that binary in the same way .   

I'm hopping that there is  a configuration on `OracalConnection` or somewhere,   for example : `((OracalConnection conn)).EncodingDetectStrategy = OracleEncodingDetectStrategy.Lagcy` ,  that can configure  it work like `OLEDB/ODBC`

**Comment by alexkeh** [comment]
Can the PL/SQL parameter and ODP.NET bind parameter be changed to an NVARCHAR2 data type?

**Comment by John0King** [comment]
> Can the PL/SQL parameter and ODP.NET bind parameter be changed to an NVARCHAR2 data type?

Did you means that change the oracle table's datatype ?   that's not possiable for us.   the db is not belong to us,  and we only can query/insert/update to a few table in that db, so there are nothing we can do to the database.

**Comment by John0King** [comment]
@alexkeh  Can you explain more specific ?   I'm new to the Oracle and  PL/Sql.   I think PL/Sql   is just a db manage tool for Oracle.

I had to use the Oledb drive now because this issue won't be solvein short time. 😒

**Comment by John0King** [comment]
@alexkeh   will this issue of the manged drive add a solution(or fix this issue) in future ?

**Comment by alexkeh** [comment]
There won't be a fix until there's a clear resolution on what the course of action should be. This is not a bug. It's more like an enhancement request. However, the ER would be to emulate other providers' behavior, which itself is not officially supported.

If you're looking for an ODP.NET fix, I would recommend opening a service request with Oracle Support. Explain the business case, the technical details and constraints, and the urgency/priority. In that process, we'll see if there's any supportable workarounds through some combination of Oracle and customer app changes. If not, there will at least be a better understanding what ODP.NET product changes would have to occur.
