### ISSUE TITLE
.NET6 RC1

### ISSUE THREAD

**Issue by kl1mm** [oracle/dotnet-db-samples#201]
Hi,
if i try to connect to my oracle database via EF-Core (6.0.0-rc.1.21452.10), Oracle.EntityFrameworkCore (5.21.3) with .NET6 RC1
i get:

`System.TypeLoadException: 'Method 'AppendIdentityWhereCondition' in type 'Oracle.EntityFrameworkCore.Update.Internal.OracleUpdateSqlGenerator' from assembly 'Oracle.EntityFrameworkCore, Version=5.0.21.1, Culture=neutral, PublicKeyToken=89b483f429c47342' does not have an implementation.'`

any ideas to work around or fix this or do i have to wait until release of Oracle.EntityFrameworkCore for 6 in Nov.?

Thanks,
mMilk

**Comment by ebicoglu** [comment]
I got the same exception in my .NET6-rc.1 project.
![image](https://user-images.githubusercontent.com/9526587/134198706-7ebd1de8-1e9e-408e-a15b-da698697a32b.png)

---

**Also I noticed that the binary has invalid version number.**

![image](https://user-images.githubusercontent.com/9526587/134198810-d10cfc85-d60a-4fe8-9182-82467bfad1b3.png)
![image](https://user-images.githubusercontent.com/9526587/134198839-1d52b43c-d056-43a2-8108-ae449e408d36.png)

**Comment by alexkeh** [comment]
The latest ODP.NET Core 3.21.3 will work with .NET 6, but the Oracle EF Core 5.21.3 does not work with EF Core 6.

Here's [Oracle's statement of direction for support .NET 6 and EF Core 6](https://medium.com/oracledevs/oracle-support-for-net-6-and-entity-framework-core-6-statement-of-direction-cfa5d1c59ff8).

There won't be a pre-release for Oracle EF Core 6, but we do plan to release production before the end of the year.

I'll have a further update and demo during the [Oracle .NET Office Hours](https://asktom.oracle.com/pls/apex/f?p=100:551:::NO:551:P551_CLASS_ID:761:) in October and the [Oracle Database World](https://www.oracle.com/database/database-world/) in October/November. Both are free to attend and virtual events.

**Comment by kl1mm** [comment]
Hey alexkeh,
thanks for the quick reply. It is super sad to hear that Oracle will not share their beta versions/ release candidates with the community.

Thanks for the event recomandations, but it sounds hard to wait until the end of the year to get it to fly.

Best regards,
mMilk

**Comment by alexkeh** [comment]
@kl1mm It would be easier to support EF Core previews if the provider model did not change with every major version. You may have noticed each time you upgrade to a new EF Core version, the previous data provider for EF Core is no longer compatible. In contrast, the .NET runtime has not changed the fundamental parts of the ADO.NET provider model since version 2, which is why you can use ODP.NET on .NET 6 previews today.

An additional challenge that makes it more difficult to support new EF Core versions quickly is that there is no official provider specification is published. Provider writers must look through the source or the tests to decipher intended behavior. If it's not clear, we have to ask the EF Core team and wait for an answer. Of course, the behavior and APIs can change anytime until the production release occurs.

Oracle has asked the EF Core team to publish and update a provider spec. However, they are very busy and are focusing their efforts on iterating EF Core quickly. When a project is moving fast, specs are hard to keep up to date and must be finalized well ahead of a release.

My purpose in writing this is to better inform you why things are the way they are. Supporting a preview release, which may break with the next EF Core preview the following month is low priority compared to what customers have told us is their top priority: have a production provider release as quickly as possible when the next EF Core version comes out. So, that's what Oracle is focused on.

**Comment by ebicoglu** [comment]
@alexkeh   thanks for the clarification. we know these things need some time. I'm here because [our framework](https://github.com/abpframework/abp) users also force us to make everything work with the newest .NET6.

**Comment by alexkeh** [comment]
@ebicoglu Noted. We'll see what we can do in the future to provide pre-release EFC support on NuGet.

I'm hoping the provider level requirements will become stable, which would make it possible to certify a working version with the next level of previews much faster.

**Comment by alexkeh** [comment]
I will demo Oracle EF Core 6 during [Oracle Database World](https://www.oracle.com/database/database-world/) at the "What’s New for .NET and Visual Studio Code Developers in Oracle Database 21c" session, which occurs October 27 (Americas) and November 3 (EMEA). This event is virtual and free. You just need to register.

I will also demo Oracle EF Core 6 at the [Oracle .NET Office Hours](https://asktom.oracle.com/pls/apex/asktom.search?oh=15141) on October 13. This event is also virtual and free. You just need to register.

**Comment by mdddev** [comment]
Hi @alexkeh, just touching base to see if you can share any updates with us? Cheers

**Comment by sdktraceur** [comment]
Dear @alexkeh, .net 6 already realized, when we can expect Oracle EF provider for them? Or better to switch to another db for a moment? Thx

**Comment by alexkeh** [comment]
We're running our functional and stress tests. So far, so good. I'll know more about the full test results next week. We're trying to release .NET 6 and EF Core 6 support this month.

ODP.NET for .NET 6 is likely to be ready before Oracle EF Core 6. Nonetheless, we'll hold ODP.NET until Oracle EF Core 6 is ready just in case ODP.NET needs a modification. ODP.NET is an Oracle EF Core dependency.

**Comment by brianphilpot** [comment]
@alexkeh any update on the release?  Working on a new project on .Net and ran into the issue described above.. was hoping to be able to move forward vs. rolling back to .Net 5.

**Comment by alexkeh** [comment]
The release is still planned for by the end of this month.

**Comment by fmessias** [comment]
Hello, @alexkeh. We have a big project upgrading to EF Core 6. Once Oracle plans were to release it until yesterday, our plan was also to upgrade together. We are just waiting for Oracle release. I think there will be many other companies waiting for that. Does Oracle have a new plan for that? Thanks.

**Comment by alexkeh** [comment]
@fmessias Sorry for the delay. We hit a few problems when setting up .NET 6 and EF Core 6 in the test environment, which delayed the critical path a bit. Functional tests completed and all look good. We have a couple of additional test suites remaining nearing completion, such as stress. We hope to analyze remaining test results by the end of this week.

**Comment by sdktraceur** [comment]
Dear @alexkeh, many thanks for information. 👍

**Comment by alexkeh** [comment]
[Oracle EF Core 6](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/6.21.4) and [ODP.NET for .NET 6](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/3.21.41) are both available on NuGet Gallery.
