### ISSUE TITLE
InfoMessage event receiving output 

### ISSUE THREAD

**Issue by netnr** [oracle/dotnet-db-samples#213]
```sql
begin
  dbms_output.put_line(sys_guid());
end;
```
Just like mssql's print

**Comment by alexkeh** [comment]
Is there a question or problem?

**Comment by netnr** [comment]
InfoMessage event is not output

**Comment by alexkeh** [comment]
InfoMessage provides event data around warning messages, Here's [more info and C# usage sample](https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/OracleInfoMessageEventArgsClass.html#GUID-DDAEF19D-72DE-4464-B792-E98DD4DFF09B).

**Comment by netnr** [comment]
Received message content: `ORA-24344: success with compilation error`, but `dbms_output.put_line(sys_guid());` no message output

**Comment by alexkeh** [comment]
If you want to send the value to ODP.NET, you need to pass it a parameter with the value. Otherwise, PL/SQL just writes the value to the buffer.

**Comment by netnr** [comment]
Therefore, I think the content of `dbms_output.put_line` will be automatically received after the `InfoMessage` event is added, without the need for `dbms_output.get_lines` to get it out through the parameters

**Comment by alexkeh** [comment]
The value I was referring to is the GUID value, not the error message. I presume the purpose of running the PL/SQL is to actually retrieve the value being output. Otherwise, it's useless to your ODP.NET app.

Do you want to share the code you use to retrieve the InfoMessage? Alternatively, you can try using the sample code and checking whether it returns the InfoMessage object as expected.

**Comment by alexkeh** [comment]
As there doesn't appear to be a bug or problem, I am closing this issue for now.
