### ISSUE TITLE
An efficient way in dealing with many Oracle connections

### ISSUE THREAD

**Issue by mihaimyh** [oracle/dotnet-db-samples#229]
I am having a requirement to build a .NET app for checking the validity of multiple Oracle database accounts passwords.
The app must check regularly if the passwords were changed in order to notify other systems to update their credentials. 

A simple

```
var connectionBuilder = new OracleConnectionStringBuilder()
{
    DataSource = connectionDetails.Name,
    UserID = connectionDetails.Username,
    Password = connectionDetails.Password,
    Pooling = pooling,
    ConnectionTimeout = 120
};
using var conn = new OracleConnection(connectionBuilder.ToString());
await conn.OpenAsync(cancellationToken);
```

should do the trick, but there is a problem: even with pooling disabled there is significant memory usage with this approach.

This is a self-contained .NET6 WorkerService app, which uses approx. 5GB RAM and jumps to approx. 9GB RAM when ORA connections are being initialized for 22 accounts.

Is there a way to do this in a more efficient way?

**Comment by alexkeh** [comment]
4 GB does seem like quite a lot of memory to use for 22 more connections. Some profiling info could tell us what is consuming so much. It could be the fact that all 22 are being requested in close succession. If that's the case, you may see performance improvement with pooling on because ODP.NET could use pre-created connections instead creating them from scratch.

Instead of opening 22 connections, you could open one connection with a SYS user that runs the following query:
`SELECT ptime FROM sys.user$ WHERE name = '<oracle user>';`

If you don't want to give your .NET app SYS user privileges, you could have a PL/SQL trigger in the DB run whenever a user updates their password. The trigger would write to a table you do have access to with the account name and last password changed date.

**Comment by mihaimyh** [comment]
@alexkeh Thanks for your input, here are some dumps.

![l13Zh](https://user-images.githubusercontent.com/549272/148729966-a85f2a01-513a-440c-b19c-9b55576294b7.png)
![1YOb0](https://user-images.githubusercontent.com/549272/148729979-302f202e-0f69-4df9-a014-770df1343aa5.png)

**Comment by alexkeh** [comment]
Do each of these users have the same credentials to ensure they are all using connections from the same pool? And has the pool been pre-populated such that the 22 connections can be serviced quickly/immediately? This can be done by increasing the Min Pool Size to a high enough level such that it will maintain enough connections.

With that said, it would be more efficient opening one connection instead of 22 to perform this check.

**Comment by mihaimyh** [comment]
No, these are different users with different passwords and possibly connecting to different databases. Do you have an example on how to use just one connection. Should I use OracleConnection as a singleton in my app? Can I change the credentials while a connection has been created/opened?

**Comment by mihaimyh** [comment]
@alexkeh Thanks for your suggestion. Why does the pools are created even with pooling disabled?
Probably is easier just to try and use sqlplus directly and check if I am able to connect using it.

**Comment by alexkeh** [comment]
Pools shouldn't be created when pooling is disabled. There can be internal objects with the term "Pool" in their names that handles general connection management. However, there will not be any pool.

**Comment by sungam3r** [comment]
Rel: #196

**Comment by sungam3r** [comment]
> There can be internal objects with the term "Pool" in their names that handles general connection management.

Well. Ok. They may be called in any way, but this does not cancel that simple fact that they for some reason consume **excessively** amount of memory.

**Comment by alexkeh** [comment]
There can be a lot of coincident factors here that make it hard to identify why memory increases so much. This is not behavior I've seen before. With that said, .NET 6 and ODP.NET 21c for .NET 6 are still fairly new. It could be a bug.

When I test opening 22 ODP.NET Core 21.5 non-pooled connections on .NET 6 in quick succession on my laptop, the app process has a net increase of 26-28 MB more memory. Before I start opening connections, the app used 14-16 MB of memory. I recorded this range over several runs.

In my experience, debugging memory usage via a discussion forum is challenging. The more efficient way is to capture memory diagnostics running on the machine and perhaps even access to the machine itself. The problems can be configuration-specific that are hard to replicate when the hardware, OS, .NET runtime are configured differently.

**Comment by sungam3r** [comment]
Agree. @mihaimyh I think we all are interested in results of investigation of your memory dumps.

**Comment by mihaimyh** [comment]
Those dumps were taken from the a production RHEL server. 
I will post new dumps, for comparison, but this time by using sqlplus to connect to the databases and not the Oracle.ManagedDataAccess.Core library.

**Comment by mihaimyh** [comment]
Added new dumps

**Comment by alexkeh** [comment]
The memory dump we need is along the lines of an ADPlus, which is a MS debugging tool. ADPlus will generate a memory dump. From that memory dump, Windows Debugger (WinDbg) can determine what .NET objects are being used more precisely.

**Comment by alexkeh** [comment]
Closing for now. I will re-open once I get the ADPlus memory dumps.

**Comment by mihaimyh** [comment]
@alexkeh ADPlus is a tool for Windows, but we are running our app on Linux, is there anything else we can use?

**Comment by alexkeh** [comment]
@mihaimyh I'm not that familiar with Linux debugging tools. Red Hat could advise the equivalent to ADPlus for its Linux platform.
