### ISSUE TITLE
Connection Pool Events / Monitoring

### ISSUE THREAD

**Issue by tinyg** [oracle/dotnet-db-samples#232]
Hi All,

When diagnosing our application, we often want to know about the status of the connection pool but AFAIK it is basically opaque. Typically the types of issues we face are:

* Someone forgets to dispose a connection
* Connections are becoming invalid due to network issues or etc
* There is a lot of contention in the connection pool
* Startup speed is slow due to connectivity issues to the database

The types of things we would like to get are:

* How many active connections are there in the pool at a given point? (usually before / after we do something specific).
* Events when the pool is changing (ie initial allocation, new connections being allocated, existing connections being closed, physical connection is assigned to a new logical connection, physical connection is released back into the pool). This is comparison to the OracleConnection.StateChange which fires when the logical connection state changes, not when the actual physical connection state changes.
* Get some kind of identifier for a physical connection as distinct to a logical connection.

Do any of these exist currently and we've missed them? I can see there are some performance counters which sort of give you some of this but not within the application...

Is it possible to request this as a feature for the future?

We have wrapped the oracle libraries to try to give us some tools in this space - maybe these ideas could be incorporated into the driver if other people think they would be helpful?

* Optionally (debug flag) query the session ID when a connection is opened so you can identify the physical session that each logical connection is tied to. This costs a query tho and presumably the connection pool already has some kind of ID for the physical connection.
* Optionally (debug flag) capture the stack trace when a connection is opened so, if the connection is not disposed properly, you can see where it came from. This is super slow in production so you need to enable it specifically but it is a lifesaver for diagnosing bad code.
* Optionally (debug flag) capture the explain plan on the way through when running a sql statement. This helps when a customer has vastly different statistics or some dubious optimisations in the database that don't occur in test environments. Its a bit tricky as some SQL needs pretty extensive rewriting to become "explainable" but can be very valuable. Would be nice if there was just an "ExplainPlan()" method on OracleCommand...
* Just try reconnecting if a connection becomes invalid while its logically open - I guess this is similar to the "Transparent Application Failover" concept except against the current database rather than a fallback. For us, just trying reconnecting to the same database and trying the sql again (if its a "safe" SQL such as a SELECT) more often than not this fixes things in a bad network environment. 

Cheers,
Chris

**Comment by sungam3r** [comment]
Rel: #123

**Comment by alexkeh** [comment]
I have a [video on using ODP.NET performance counters](https://www.youtube.com/watch?v=mNwaYIazxlw). It's mostly a discussion of how to configure the counters and use them via Windows PerfMon. It briefly discusses programmatic usages via the PerformanceCounter class is System.Diagnostics though I don't go into detail. Nonetheless, as long as you turn the specific ODP.NET counters on, you should be able to retrieve the NumberOfActiveConnections stats programmatically, which is what I believe you're looking for.

Yes, the ODP.NET connection is opaque when it comes to tracking individual connections. Most developers don't need to track individual connections. If they do, they often do not use connection pooling or create their own pooling algorithm.

If startup is slow, you can keep the Min Pool Size high to avoid connection storms. For example, if many people log on to an app when the work day begins, a high Min Pool Size will prevent the pool from being drained from the lack of overnight activity. You can also set a higher Incr Pool Size so that the pool can grow quickly.

You can also slow how many connections the listener handles by using the connection rate limiter properties in sqlnet.ora.

Another possibility is to use DB Resident Connection Pooling if connections are often short-lived. It's a server pool for your connections.

If connections are becoming invalid, then understanding why that is occurring will be helpful. If they become invalid during planned outages, you can shutdown or failover your DB with a drain timeout or with the TRANSACTIONAL parameter. If you have ODP.NET Fast Connection Failover enabled, ODP.NET will stop new connections to the instance shutting down, clear out idle pooled connections to that instance, and dispose existing connections to that instance when they are returned to the pool. This method should lead to a graceful shutdown/failover experience without invalid connections.

For unplanned outages, Application Continuity will recover connection and transactional state. This feature is only available in unmanaged ODP.NET, but will be coming to managed ODP.NET and ODP.NET Core.

**Comment by tinyg** [comment]
Hi Alex,

Thanks for the video - I think that does help somewhat. I would say getting it configured looks like a fair bit of work tho - I think we might have trouble getting some customers to run through it.

Also I guess there's the issue of having to know when you want to use it whereas often we're in the mode of looking back afterwards to try to work out what went wrong.

My experience with performance counters is that they tend to start using a lot of memory over time - are you able to comment on what would happen if we just let the performance counters run all the time? Ideally we could be recording some metrics off to a centralised metrics tool on a constant basis so we can see if the behaviour of the system changes.

I think the server-side pooling would also be helpful for us so I might have a look at that, but I guess there's no way to do custom client side pooling with the built in server-side pooling?

The value of having an ID for soft vs hard connects is that you can work out what was going on after the fact if you have the ids in a log.

I guess if I look at the specific experience that caused me to add this comment / issue:

Our web application typically takes approx 20 seconds to start from a hard restart, approximately half of that is usually due to opening new hard oracle connections when the first soft connection occurs - our default minimum pool size is 5 so there's approx 3 seconds per connection. In the last few days we saw the startup time blow out to 5 minutes. Given nothing else had changed in the startup logic, my assumption is that that is caused by the oracle connections taking longer to establish than usual. To test this theory, I wanted to measure how long the initial pool took to connect and also whether that was 1 very slow connection and then 4 fast ones, or 5 slow connections. The problems I had trying to do this were:

* Identifying the "first" connection is actually quite difficult - because we're using pooling, we don't do any specific "make a connection just to establish the pool", we just do our business and whatever happens first will allocate the pool. We could probably use a flag or something to remember this and happy to chalk this down as "our problem" I guess. 
* Having identified the first connection, I then need to time it but, since its just OracleConnection.Open, then all I get is a "total time" not per hard connection information.
* If the first connect is still ok then I need to know if any other hard connections occurred at startup time (ie the pool wasn't big enough) and how long those took.

In this case, it turned out that our IT department had made a network change that inadvertently caused each connection to take much longer than usual, but we were only able to identify it due to other work.

What stood out was that, if there was a static event similar to the static HAEvent event on OracleConnection, then it could have told me what was happening quite easily. eg:

`
public enum OracleConnectionPoolState {
   HardOpen,
   HardClose,
   SoftOpen,
   SoftClose
}

public class OracleConnectionPoolEventArgs : EventArgs {
    long HardConnectionID { get; }
    long SoftConnectionID { get; }
    OracleConnectionPoolState StateChange { get; }
}

public class OracleConnection {

    private static long _idGen = 0;

    public OracleConnection() {
       this.SoftConnectionID = Interlocked.Increment(_idGen);
       // ...
    }

// ...
    long? HardConnectionID { get; }
    long SoftConnectionID { get; }
    static event EventHandler<OracleConnectionPoolEventArgs> ConnectionPoolStateChange;
// ...
    public void Open() {
        // ... 
        this.HardConnectionID = this.underlyingConnection.ID;
        // raise appropriate ConnectionPoolStateChange event.
        // ...
    }

   public void Close() {
      //...
      // raise appropriate ConnectionPoolStateChange event.
      this.HardConnectionID = null;
   }
// ...
}
`

Cheers,
Chris

**Comment by alexkeh** [comment]
In your scenario, I would turn on ODP.NET tracing instead of performance counters. Tracing gives you a granular look into how fast each internal ODP.NET operation is performing as it collects timestamp. In my experience, it's usually one slow operation or the same repeating slow operation that is causing the problem. It then becomes easier to diagnose the root cause.

ODP.NET can turn on tracing programmatically

```
OracleConfiguration.TraceFileLocation = @"<directory>";
OracleConfiguration.TraceLevel = <level>;  // Set to 7 for Core and Managed or 127 for Unmanaged
```
You can also turn on these same parameters via the .NET configuration file.

Configuring performance counters does require some work. They are not setup and enabled by default. This is in line with typical .NET and Windows practices, such as no default machine-wide configuration, no enablement by default, and no PerfMon collection by default.

With that said, partners can create scripts to automate and customize all of these steps if they'd like. It doesn't have to be manual for partner end users. The PowerShell script is customizable.

I've never done any performance testing with perf counters on. A big reason why is that perf counters are not meant to be used at run-time on a typical basis. It's used for diagnosing a problem. Once the problem is diagnosed and fixed, counters disabled. 

Some additional challenges is what exactly can an ADO.NET drivers improve with counter performance tune. Most of the code is part of .NET. The ADO.NET just bumps the counters and that's about it.

The exact performance difference will also depend on the which and how many counters you enable. It's a good practice to only enable to counters you exactly need to diagnose the likely problem instead of all of them.

You can have your own custom client-side pooling working with DRCP. ODP.NET pooling and DRCP are independent of each other. It's just not very common for customers to create their own pools nowadays, which is why the doc doesn't really discuss that option.

Here's the [ODP.NET doc on performance counters, followed by DRCP](https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/featConnecting.html#GUID-4FA1C8D3-195B-4D7A-9E9D-9FB74C7F5312).
