### ISSUE TITLE
network transport: ssl failure in parsing wallet location

### ISSUE THREAD

**Issue by djunibert** [oracle/dotnet-db-samples#258]
network transport: ssl failure in parsing wallet location

**Comment by alexkeh** [comment]
Usually, this is due to a problem with the Oracle wallet location setting. It could be set to the wrong location. have a syntax typo, or you may need to enable Load User Profile if you are storing the wallet on the file system. If you have more than one place on your machine the wallet location is set, it's possible ODP.NET is finding that other location first and using it.

It will more straightforward to diagnose if you provide your ODP.NET trace files, which will tell us where ODP.NET is looking for the wallet.

Here's the code snippet to add to enable tracing:
```
OracleConfiguration.TraceFileLocation = @"C:\traces";
OracleConfiguration.TraceLevel = 7;
```

**Comment by alexkeh** [comment]
Closing for now. I'll reopen when more info is provided to diagnose.
