### ISSUE TITLE
 .NET 7 support

### ISSUE THREAD

**Issue by ssougnez** [oracle/dotnet-db-samples#264]
Now that .NET 7 is available, do you have any idea when the provider will support it?

Thanks

**Comment by alexkeh** [comment]
We're in the process of testing [ODP.NET Core 3.21.80](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/3.21.80) with .NET 7 now that it's available to download. In our past ODP.NET Core testing with the .NET 7 preview/RC releases, we haven't see any issues of concern lately. If we don't see any issues in this latest test round, we'll certify the 3.21.80 release for .NET 7. In fact, that's Oracle's current expectation.

If you'd like, you can start developing with ODP.NET Core 3.21.80 with .NET 7 today. At worst, if we find a bug or two, we'll patch with a follow on release.

**Comment by ssougnez** [comment]
Hello,

I'm not entirely sure that I understood correctly.
I'm currently using the package Oracle.EntityFrameworkCore 6.21.61.
That's this provider that I expect to work with .NET 7 (which is not the case currently).

Do you have maybe a pre-release or something of that NuGet in order to test the upgrade of my project to .NET 7 ?
If not, maybe a planned release date?

Thanks

**Comment by alexkeh** [comment]
@ssougnez I'm changing the issue title back to the original text because I have already provided comments and Oracle planning for .NET 7. People have upvoted and linked to to this request based on the original title. And there is no doubt there is interest in ODP.NET for .NET 7 separate from EF Core.

I will comment on the topic here nonetheless. If further discussion is desired, a separate issue thread should be created.

EF Core 7 has some significant changes for provider writers to make. These changes occurred throughout the preview releases and even during the RC releases. That is in contrast with .NET 7, which has kept its ADO.NET support fairly stable for provider writers.

The Oracle .NET team is working on making those changes (and fixing some of the existing Oracle EF Core bugs too). We plan to release an Oracle EF Core 7 provider by the end of this year on NuGet Gallery.

**Comment by ssougnez** [comment]
And I guess no pre release version are planned? Maybe to help you find issues?

**Comment by alexkeh** [comment]
No pre-release is planned. We're going straight to production.

**Comment by ssougnez** [comment]
Well, then I'll wait :-)

Thanks

**Comment by alexkeh** [comment]
Oracle has completed certification. ODP.NET Core 21.8 is now officially certified for .NET 7.
