### ISSUE TITLE
!IsNullOrWhiteSpace CLOB column bug

### ISSUE THREAD

**Issue by Xor-el** [oracle/dotnet-db-samples#272]
executing the query below
```csharp
return await _db.Books.Where(x => !string.IsNullOrWhiteSpace(x.Metadata)).ToListAsync(cancellationToken);
``` 
against a `CLOB` column generates the following SQL 

```sql
SELECT "b"."Id", "b"."AuthorId", "b"."Metadata", "b"."Title"
FROM "Books" "b"
WHERE (("b"."Metadata" IS NOT NULL) AND (LTRIM(RTRIM("b"."Metadata")) <> ''))
```
which throws `ORA-00932: inconsistent datatypes: expected - got CLOB` when run against the database.

note that the code generated by the inverse of the LINQ query (without the `!` symbol before `string.IsNullOrWhiteSpace`) works ok.

**Repro Project**

https://github.com/Xor-el/EFCore-Oracle-Buggy-Demo/tree/!IsNullOrWhiteSpace-CLOB-column-bug

**Provider and version information**

EF Core version: Oracle.EntityFrameworkCore 7.21.8
Database provider: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Target framework: .NET 6.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.4.3

**Comment by alexkeh** [comment]
JSON is not currently support in the Oracle EF Core 21.8 version. Oracle is planning to add this support soon.

This issue exists as a bug because the overarching enhancement has not been added. Bug 34989781 has been filed to track this issue. The parent issue is https://github.com/oracle/dotnet-db-samples/issues/259.

**Comment by alexkeh** [comment]
Fixed with Oracle EF Core 8
