### ISSUE TITLE
Oracle.ManagedDataAccess.Core - Retry Count not working

### ISSUE THREAD

**Issue by dmitriy-shleht** [oracle/dotnet-db-samples#331]
`Oracle.ManagedDataAccess.Core` v3.21.120

We have two database servers, and we need to connect to the second server if the first server fails.

Here is our connection string:
```
User Id=TEST;CONNECTION TIMEOUT=10;HA Events=true;Data Source=(DESCRIPTION =
 (TRANSPORT_CONNECT_TIMEOUT=10) (RETRY_COUNT=1)(RETRY_DELAY=5)
 (ADDRESS_LIST =
(LOAD_BALANCE=on)
( ADDRESS = (PROTOCOL = TCP)(HOST=172.30.2.211)(PORT=1521)))
 (ADDRESS_LIST =
(LOAD_BALANCE=on)
( ADDRESS = (PROTOCOL = TCP)(HOST=172.30.2.212)(PORT=1521)))
 (CONNECT_DATA=(SERVICE_NAME = odb)))
```

The `RETRY_COUNT` parameter is not working as expected. When we try to open the connection initially, we get a `Connection request timed` out exception, and when we try to open the connection again, we successfully connect to the database server. How can we make it so that it connects to the second server (172.30.2.212) immediately without throwing an exception?

**Comment by alexkeh** [comment]
Your TRANSPORT_CONNECT_TIMEOUT is the same value as your CONNECTION TIMEOUT. When the connection attempt to 211 fails, so does ODP.NET's overall attempt to connect.

Increase your ODP.NET connection timeout and/or decrease your TRANSPORT_CONNECT_TIMEOUT. The latter can be specified in milliseconds so that you can try the second server very quickly if the first server can't deliver a connection quickly.

**Comment by dmitriy-shleht** [comment]
Yes it worked, thank you very much

**Comment by alexkeh** [comment]
LOAD_BALANCE enables load balancing between addresses at connection time.
