### ISSUE TITLE
Boolean data type not working on 11g

### ISSUE THREAD

**Issue by iulianb** [oracle/dotnet-db-samples#363]
```
PROCEDURE "TESTBOOL" (
  "PARAM1" IN BOOLEAN, 
  "PARAM2" OUT BOOLEAN) IS
BEGIN
	PARAM2 := PARAM1;
END;
```

```csharp
string constr = "<Connection String>";
OracleConnection con = new OracleConnection(constr);
con.Open();

OracleCommand cmd = new OracleCommand("TESTBOOL", con);
cmd.CommandType = CommandType.StoredProcedure;

OracleParameter oparam = cmd.Parameters.Add("PARAM1", OracleDbType.Boolean);
oparam.Direction = ParameterDirection.Input;
oparam.Value = "True";

OracleParameter oparam2 = cmd.Parameters.Add("PARAM2", OracleDbType.Boolean);
oparam2.Direction = ParameterDirection.Output;

cmd.ExecuteNonQuery();

Console.WriteLine(oparam2.Value.ToString());
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="6.21.130" />
  </ItemGroup>

</Project>
```

This doesn't work on `Oracle Database 11g Release 11.2.0.3.0 - 64bit Production`. Fails with `ORA-03115: unsupported network datatype or representation`

**Comment by iulianb** [comment]
tried with `Oracle.ManagedDataAccess.Core 2.19.220`, same outcome.

**Comment by alexkeh** [comment]
Reviewing the doc, I was reminded that [managed ODP.NET only supports PL/SQL Booleans with Oracle DB 12.2 and higher](https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/OracleBooleanStructure.html#GUID-B5B5ACB7-14A5-43D5-B8A9-7D0046D40E2E). Since ODP.NET Core shares much of the same code with managed ODP.NET, this should also apply to ODP.NET Core. I'll confirm with my dev team and update the next version of the doc to reflect this.
