### ISSUE TITLE
Oracle.EntityFrameworkCore 8.0 不再支持19c以下版本数据库了嘛

### ISSUE THREAD

**Issue by wangxb01** [oracle/dotnet-db-samples#408]
![image](https://github.com/user-attachments/assets/62c715b0-5557-4875-90ae-2354f8066801)
![image](https://github.com/user-attachments/assets/5a68b7cd-9c07-4163-b707-9ff61f54d4aa)
请问19c 以下版本在 8.0版本中不再支持了嘛

**Comment by alexkeh** [comment]
Oracle Database 18c and earlier versions have all reached end of life. They are not supported by Oracle anymore, in general.

Oracle EF Core introduced the new OracleSQLCompatibility enum with EF Core 8. Because it is a new API, we could not support older, out of support DB versions, such as 18c or 12g.
