### ISSUE TITLE
NUMBER(4,0) is converted to byte

### ISSUE THREAD

**Issue by nilendrat** [oracle/dotnet-db-samples#41]
We are using 12c database with db first methodology , When the db is scaffolded number4(4,0) is coverted to byte , instead of int.

**Comment by alexkeh** [comment]
Yes, byte is the default mapping between NUMBER(4,0). If you would like to change the default mapping behavior, use Fluent API or Data Annotations to do so.

**Comment by nilendrat** [comment]
Thank you for the reply , but as mentioned in the oracle documentation **Number(4,0)** is converted to **Int16**, but with **Oracle.EntityFrameworkCore** latest version the field is converted to **byte** .  

**References** 
[](https://docs.oracle.com/database/121/ODPNT/entityEDMmapping.htm#ODPNT8275)
[](https://docs.oracle.com/database/121/ODPNT/entityDataTypeMapping.htm#ODPNT8300)

With fluent API each time a scaffold command is executed , the configurations are erased . 

TIA

**Comment by alexkeh** [comment]
Oracle.EntityFrameworkCore and Oracle EF6 do not have the same default data type conversions. They are two different products, just like EF6 and EF Core are two different ORMs, despite having similar names and purposes.

**Comment by nandagoban08** [comment]
In oracle, if you assign NUMBER(4,0) to a variable you can add up to 1-9999 into the database.
In C#, If you assign a byte to a variable you can only add up to 1-256 into the memory.
If Oracle.EntityFrameworkCore generates Number(4,0) as a byte in DBContext automatically, It's Huge bug and it 'll give a problem to your solution in future. If possible find to override the DBConext but I won't recommend  or otherwise please use another ORM like Dapper https://www.nuget.org/packages/Dapper.Oracle/

**Comment by nirmalmax** [comment]
@alexkeh we are also having the same issue , we are having a version upgrade from ef6 to ef core , due to .net core migrations as ef6 is not supported by .net core

With ef6 , Number(4,0) is converted to , Short in c#. But however in ef core it is converted to a byte field which .  But with your feedback , what would u suggest to do with exciting data ?

**Comment by alexkeh** [comment]
Keep in mind data type mapping needs to be consistent for Migrations and Scaffolding. If Oracle changes the default mapping for Scaffolding to minimize later manual changes, it will mean more manual mapping change work for Migrations users.

We realize customers customizing and changing mapping would be required one way or the other. We asked the Microsoft EF Core team what is the best strategy. Their recommendation was to minimize mapping changes needed for Migrations, which is the more common use case. That does mean that Scaffolding requires more manual mapping customization.

EF6 and EF Core, while sharing a similar name and both being ORMs, are very different. Portability is not guaranteed. There are feature differences between the two.

**Comment by alexkeh** [comment]
One way to resolve this scaffolding data type mapping issue is to use  the EF Core Value Conversions features. This thread discusses using it with Oracle EF Core. https://community.oracle.com/thread/4293559
