### ISSUE TITLE
Scaffold-DbContext generate type problem

### ISSUE THREAD

**Issue by vn506138** [oracle/dotnet-db-samples#43]
DDL:
```
CREATE TABLE "TABLE1" (
    "KEY1"    VARCHAR2(20 CHAR),
    -- sbyte, -128 to 127
    "NUM2"    NUMBER(2, 0),
    -- short, -32,768 to 32,767
    "NUM3"    NUMBER(3, 0),
    -- short, -32,768 to 32,767
    "NUM4"    NUMBER(4, 0),
    -- int, -2,147,483,648 to 2,147,483,647
    "NUM5"    NUMBER(5, 0),
    -- int, -2,147,483,648 to 2,147,483,647
    "NUM9"    NUMBER(9, 0),
    -- long, -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807
    "NUM10"   NUMBER(10, 0)
);
```
[Integral numeric types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types)

Scaffold-DbContext
```
public partial class TABLE1
{
    public string KEY1 { get; set; }
    public byte? NUM2 { get; set; }
    public byte? NUM3 { get; set; }
    public byte? NUM4 { get; set; }
    public short? NUM5 { get; set; }
    public int? NUM9 { get; set; }
    public int? NUM10 { get; set; }
}
```

**Comment by alexkeh** [comment]
The types appear to be mapping as documented.
https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/EFCoreREDataTypeMapping.html#GUID-4FF3A9A3-AE49-431B-A4FB-31F8C53FCCF5

ODP.NET EF Core wants to maintain a consistency with migrations and scaffolding such that mappings stay consistent when undertaking either process. Because Oracle data types and .NET data types have different sizes, the default mappings will never be perfect for every situation. You can modify the .NET data types if you wish to use different ones.
