### ISSUE TITLE
oracle dataprovider timeout after oracle restart

### ISSUE THREAD

**Issue by kosnkow** [oracle/dotnet-db-samples#6]
https://stackoverflow.com/questions/49030744/oracle-dataprovider-timeout-after-oracle-restart#49030744

**Comment by alexkeh** [comment]
Answered on StackOverflow

**Comment by kosnkow** [comment]
there is no answer yet, can you check  ?

**Comment by alexkeh** [comment]
When the DB restarts, do you remove the invalid connections from the pool using a ClearPool type API or Oracle Fast Connection Failover (FCF)? If the answer is no, that's the likely reason for the timeout or error when pooling is on.

The invalid connections remain in the pool and the app is picking up one of these connections.

The ClearPool APIs and/or FCF are intended to resolve this HA issue. ClearPool is a manual process unfortunately. Most customers prefer to automate connection cleanup with FCF.

To use FCF, your DB needs to enable Fast Application Notification, then turn on FCF on the server side. On the client side, you just turn HA Events=true in the connection string, which should already be turned on by default if you are using ODP.NET 12.2.

To learn more about FCF and other Oracle .NET HA technologies, I recommend watching [this video](https://www.youtube.com/watch?v=HLrsCzVA1J0) or reading the [FCF part of the ODP.NET doc](https://docs.oracle.com/cd/E85694_01/ODPNT/featRAC.htm#ODPNT8180).

**Comment by alexkeh** [comment]
For some reason, StackOverflow thought my original post was spam, deleted it, and failed to inform me they deleted it. I just reposted my answer on SO here.

**Comment by kosnkow** [comment]
was able to reproduce this issue locally, installing oracle locally, and with turning HA events=true localy the problem was gone. 
Unfortunately this did not work on production since probably as you said this option is not turned on on oracle server, I am afraid we can not force the client to turn this option on.

about the clearing the pool, in my SO question there is in finally section 
 OracleConnection.ClearPool(this.Connection);
I also tried putting this in catch section but that did not help. 
I read that this way connection is marked to be removed from the pool, and when connection will be close it will be removed from the pool but this also did not work for me
also waiting for this like 5 minutes did not clear the broken connection from the pool, so any advice what else I can check ?

**Comment by alexkeh** [comment]
The behavior you describe sounds like ODP.NET 11.2 or earlier. The previous versions would repopulate the pool back to the Min Pool Size immediately after the ClearPool() call. ODP.NET 12c versions wait for the next OracleConnection.Open(), which presumably occurs when the DB is back up to dispense valid connections.

Here's more info on [ClearPool](https://docs.oracle.com/cd/E85694_01/ODPNT/ConnectionClearPoolCtor1.htm) from the 12.2 doc.

**Comment by kosnkow** [comment]
I updated my question on SO: 

I use:

Oracle.ManagedDataAccess.EntityFramework.12.1.022
Oracle.ManagedDataAccess.12.1.022
product\12.1.0\client_1\odp.net\bin\4\Oracle.DataAccess.dll
when program is running I stop the OracleServiceORCL service

then with first attemp to openConnection I got:

ORA-03113 end of file on communication channel
with second attempt I got:

ORA-12514 TNS:listenere does not currently know of service requested in connect descriptor
and with third one and every next one I got Connection request timned out

Now when I run the OracleServiceORCL on, my program still is throwing time out exception

when I restart my program, it works.

**Comment by alexkeh** [comment]
If you try to connect before the DB is up, ODP.NET will still populate the pool. Unfortunately, these will be invalid connections since there is no running DB to connect to. If the DB server is brought up at this point, as what exists in your scenario, only **newly** created connections will be valid. The pool will still contain invalid connections.

The takeaway is do not try to connect when the DB is down. You defeat the purpose of FCF.

If this is an Oracle RAC deployment, the remaining nodes will deliver valid ODP.NET connections. If this is Data Guard, ODP.NET can "pause" these new connection requests so that connections are not actually attempted until time is given for the standby DB to come up. This "pause" is enabled through Service Relocation Connection Timeout. That's how FCF is supposed to work in conjunction with Oracle HA technologies.

**Comment by kosnkow** [comment]
hello Alex, I still think there must be something around the code I will
try to explain why

in SO question I provided trace log and we can see there

(ENTRY) OracleConnection.ClearPool()\n"
and

(EXIT)  OracleConnection::ClearPool()\n"


but if we check the code between these lines, there is something like:

      try

      {

        OracleConnection.ValidateAdminValues(conn);

        ConnectionDispenser.ClearPool(conn.m_opoConCtx, false, false);

      }

      catch

      {

      }

which is very intressting, I believe that
OracleConnection.ValidateAdminValues(conn);
throws an exception which empty catch removes.

why ? because if you looked into  ClearPool we can see another trace
entry  (ClearPool)
Pool Id = " + (object) this.m_poolId + " Removed PooledConCtx= " + (string)
(object) local_9.GetHashCode() + "\n" p>
which has never showed in my trace log file.

anyway, I would like you to ask if you could provide me source code so I
can debug the oracle provider ? I can try to recreate class by class, but
this will take me hours.

2018-03-05 20:18 GMT+01:00 Alex Keh <notifications@github.com>:

**Comment by alexkeh** [comment]
FCF is a feature of Fast Application Notification (FAN). FAN only requires that Oracle clusterware be used to be able to propagate messages in case the DB server goes down. RAC is not a necessary condition for FAN. People think RAC is required because FAN and RAC are often discussed together. That's only because they are often used together and RAC was one of the earliest consumers of FAN.

You can use FCF and FAN with single instance, which can be useful in a Data Guard switchover, for example.

Unfortunately, I can't provide any ODP.NET source code. ODP.NET is not open source.

**Comment by kosnkow** [comment]
The pitty you closed it, there is still a problem and seems other people
also have seen it
https://stackoverflow.com/questions/23613960/odp-net-connection-pooling-issues-fault-tollerance-after-database-goes-down

2018-03-09 1:50 GMT+01:00 Alex Keh <notifications@github.com>:

**Comment by alexkeh** [comment]
The folks in the other SO thread were not using FCF. In fact, they were encountering the exact problem FCF was created to solve. I recommended they use it if they want to eliminate the problem of invalid connections after the DB is rebooted.

I'm happy to re-open this issue.

**Comment by alexkeh** [comment]
If there's no additional follow up to this question, I will close this issue in the next few days.
