### ISSUE TITLE
EF Core 3.1 Beta 2: Slower performance when using Date data type

### ISSUE THREAD

**Issue by alexkeh** [oracle/dotnet-db-samples#80]
I can't find the link to Oracle forum anymore (and anyway, I find them pretty not user friendly), so I'll post my issue here. As I said in my previous post, I'm experiencing major performance degradation (or simply an issue) when using dates. 

I have the following query:

```
var doorCrossings = await _oracleContext
    .DoorCrossings
    .AsNoTracking()
    .Where(dc => dc.Matricule == user.Matricule && dc.CrossingAt.Date == date.Date)
    .OrderBy(dc => dc.CrossingAt)
    .ToListAsync();
```

Note that I'm using the "Date" property of the dates because I don't want to take the time into account.

The "Matricule" field is "varchar2(16)" and "CrossingAt" is a "Date". There is an index in the table based in these two fields. When running this query in the .NET 2.2 version, it is very fast (1-3s, there are millions of lines in this table).

However, when running the exact same query on the exact same database with the version 3.1 of the provider, the query execution never ends. I put a break point to the next line and it never gets hit and I don't see any exception in the output.

To help investigating, I put the logging level to "Information". When doing it with the 2.2 version, I see the query but I don't see it with the 3.1 version. I tried removing the second part of the condition and then, I see the logs (I don't get the results but there is no index on the "Matricule" field alone so it can be that it takes a long time to execute).

The part date of the generated query in 2.2 is

`AND ("TRUNC"(FIELD) = :date_Date_1)`

I replaced the real name of the field by "FIELD" for confidentiality reason.

So I don't know how to investigate this further but it seems that there is an issue with dates.

_Originally posted by @ssougnez in https://github.com/oracle/dotnet-db-samples/issues/49#issuecomment-660342024_

**Comment by alexkeh** [comment]
@ssougnez
The ODP.NET trace will record the SQL being executed. You can turn on tracing

**Comment by ssougnez** [comment]
Hi, thanks for creating this ticket in GitHub :-)

I did what you said but the issue is that it logged anything that my application is doing and... it's doing much haha
However, I tried to extract the info you needed.
Here is the SQL query that causes issues:

```
SELECT {FIELDS}
FROM "{SCHEMA}"."{TABLE}" "d"
WHERE (("d"."{MATRICULE}" = :user_Matricule_0) AND (TRUNC("d"."{DATE}") = :date_Date_1))
ORDER BY "d"."{DATE}"
```

I modified it for confidentiality purpose but:

* {FIELDS} is just a regular list of field like "d"."Field1", "d."."Field2", ...
* {SCHEMA} and {TABLE} are simply the full name of the table
* {MATRICULE} and {DATE} are simply field name

I looked for the value of ":user_Matricule_0" and ":date_Date_1" in the trace file but could not find them. I guess it could see them by setting a property in .NET, but at the end, matricule is a small string such as 04392 and the date is a regular date.

I tried to be patient and used a stopwatch to monitor the execution and the query took 6 min to execute o_O 
Note that I also tried the following condition:

`.Where(dc => dc.Matricule == user.Matricule && dc.CrossingAt == date)`

So, without the ".Date" component and the query took 57 sec to execute. 
Still way too much but better... 
The SQL generated is this:

`WHERE (("d"."{MATRICULE}" = :user_Matricule_0) AND ("d"."{DATE}" = :date_1))`

I tried to execute this query in SQL developer tool by replacing ":date_1" by "to_date('2020-07-18 00:00:00', 'yyyy-mm-dd hh24:mi:ss')". It took 0.055s to execute. 

Therefore I tried to execute the very first query like this:

`WHERE (("d"."{MATRICULE}" = '04736') AND (TRUNC("d"."{DATE}") = to_date('2020-07-18', 'yyyy-mm-dd')))`

And it took 0.154s to execute.

Note that I don't think that it is a data type related issue because I tried removing the date part of the condition and it still took a very long time to execute while it takes 0.1s in SQL developer tool.

Just to be sure, all the tests above have been executed with the 2.2 and the 3.1 version and all the 2.2 queries got executed in acceptable timing while the 3.1 ones took forever. That's weird because the queries I try to execute are pretty basics so I'm surprised that I'm the only one impacted by this issue.

**Comment by ssougnez** [comment]
I did some more investigation by creating a simple console app that only execute this request and logs it.
The result is the same, still very slow.
Moreover, by default, I'm setting the pooling to `false` in the connection string because I was experiencing issue of failed connection in 2.2, so I tried with pooling but the result is the same.
Another interesting information, the query returns 0 record, it is normal, so I guess the issue does not occur during the deserialization phase.
I can send the logs files by email if you provide me one but one thing I notice is that:

**Without pooling**

The last lines in the log files are:

2020-07-18 11:48:44.299897 TID:1   (PRI) (TTC) (EXT) TTCExecuteSql.WriteOall8Message()
2020-07-18 11:48:44.299904 TID:1   (PRI) (TTC) (EXT) TTCExecuteSql.SendExecuteRequest()
2020-07-18 11:48:44.299911 TID:1   (PRI) (TTC) (ENT) TTCExecuteSql.ReceiveExecuteResponse()
2020-07-18 11:48:44.300182 TID:1   (PRI) (BUF) (COBP.GET) (poolid:1) (key:65535) (bufid:9) (count:6) (OraBufReader.GetDataFromNetwork)

When I check this, the query was running for 3-4 minutes, so nothing gets logged during the "waiting phase".

**With pooling**

The only difference is that the log file gets updated every 20 sec with this:

2020-07-18 11:59:19.926133 TID:9   (PRI) (TUN) OracleTuningAgent::DoScan(): No pools identified for optimization. Stay in SCAN state.
2020-07-18 11:59:39.930885 TID:9   (PRI) (TUN) OracleTuningAgent::DoScan(): No pools identified for optimization. Stay in SCAN state.
2020-07-18 11:59:59.936206 TID:9   (PRI) (TUN) OracleTuningAgent::DoScan(): No pools identified for optimization. Stay in SCAN state.
2020-07-18 12:00:19.940800 TID:9   (PRI) (TUN) OracleTuningAgent::DoScan(): No pools identified for optimization. Stay in SCAN state.
2020-07-18 12:00:39.946602 TID:9   (PRI) (TUN) OracleTuningAgent::DoScan(): No pools identified for optimization. Stay in SCAN state.
2020-07-18 12:00:59.952925 TID:9   (PRI) (TUN) OracleTuningAgent::DoScan(): No pools identified for optimization. Stay in SCAN state.

**Comment by ssougnez** [comment]
Me again.

I just checked the available NuGet packages in my .NET Core 2.2 app and noticed that "Oracle.EntityFrameworkCore 2.19.80" has been recently released.

Therefore, I upgraded it and... my queries got way slower all of a sudden. It does not seem to be as slow as with the version .NET Core 3.1 compatible version but I can see a real difference between the query execution times between the version 2.19.70 and the version 2.19.80.

Maybe it would be easier for you to track down what changed between these two versions than between the 2.2 and 3.1 compatible.

**Comment by alexkeh** [comment]
Let me follow up with my dev team to see if they have enough info to identity the root cause. It does sound like there may be multiple areas causing the slow down. You indicated the Oracle EF Core 3.1 beta 1 had this slow down. That beta used ODP.NET 2.19.70. The beta 2 uses the 2.19.80 version.

It may be most expedient if you can send us a test case (dotnet_us(at)oracle.com) or email us the location to download the test case so that we can reproduce the problem in house and conduct diagnostics end to end to find the root causes.

A few follow up questions:
1) What is your Oracle DB version?
2) How long does it take the query to run with EF Core 2.2? You said it was an acceptable time, but did not indicate what range is acceptable. The actual time is a bit less important than what factor slower is the current provider. 
3) Is this the only query that takes a long time to run? Or have you experienced slower performance across all your queries?
4) How much slower is your EF Core 2.2 with ODP.NET 2.19.80 vs. 2.19.70?

**Comment by ssougnez** [comment]
Sorry, didn't find much time to answer yet. I'll do so today or tomorrow :-)

**Comment by ssougnez** [comment]
Hello,

the oracle DB version that we're using is "Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production".

For the location to download the tests, what do you want exactly ?
If you want the C# code, I can upload it somewhere but basically, it's just the execution of a single query (that you'll find in the mail I just sent to the email address you gave me).
Moreover, without the database behind, it won't be very useful.

Now, while writing this answer, I noticed that I wrongly used the version "2.2" in my speech as I wanted to refer to EF Core 2.2 and not .NET Core 2.2. 
However, I did perform some tests and here are the results:

* .NET Core 3.1 - EF Core 2.2.6 - Oracle.EntityFrameworkCore 2.19.70: 69ms, 67ms and 70ms
* .NET Core 3.1 - EF Core 2.2.6 - Oracle.EntityFrameworkCore 2.19.80: 50294ms, 23922ms and 23783ms
* .NET Core 3.1 - EF Core 3.1.6 - Oracle.EntityFrameworkCore 3.19.0-beta2: 1.234.006ms (20 minutes)... I guess you can understand that I only did one test.

For information, I retrieved the number of records in the table and it is up to 17.582.418 (I'm just a client of the database, I'm not maintaining it...).
And to answer your question, I did the same tests on two other tables, one with approximately 6000 records and one with 419 000 000 records.
The queries performed about the same with the first table but the performance degradation occured with the other table.
It might be related to the number of records contained in the table (note that all three queries return no more than 10 records, so it does not seem linked to the number of records retrieved).

Btw, I did some researches and as you know, I'm not the only one (https://community.oracle.com/thread/4339431?start=0&tstart=0)
Maybe that person and I share something in common in our architecture/code that could explain this.
Did you already try the provider with a table containing several millions of records?

During my experimentation, I also noticed something extremely weird.
I was testing with this request:

```
var doorCrossings = dbContext
    .DoorCrossings
    .AsNoTracking()
    .Where(dc => dc.Matricule == "XXXXX" && dc.CrossingAt.Date == date.Date)
    .OrderBy(dc => dc.CrossingAt)
    .ToListAsync();
```

And this was very slow (30s)... Even with the 2.19.70 version.
The logs file associated with that query is "with-literal-2.19.70.trc" (see my mail).

Then, I tested this:

```
var matricule = "XXXXX";

var doorCrossings = dbContext
    .DoorCrossings
    .AsNoTracking()
    .Where(dc => dc.Matricule == matricule && dc.CrossingAt.Date == date.Date)
    .OrderBy(dc => dc.CrossingAt)
    .ToListAsync();
```

And it took... 1.6 seconds o_O
The logs file associated to that query is "with-variable-2.19.70.trc" (see my mail).

The location in the logs where I see a huge delay with the literal is:

> 2020-07-24 15:42:09.684501 TID:1   (PRI) (TTC) (EXT) TTCExecuteSql.WriteOall8Message()
> 2020-07-24 15:42:09.684509 TID:1   (PRI) (TTC) (EXT) TTCExecuteSql.SendExecuteRequest()
> 2020-07-24 15:42:09.684523 TID:1   (PRI) (TTC) (ENT) TTCExecuteSql.ReceiveExecuteResponse()
> 2020-07-24 15:42:09.684810 TID:1   (PRI) (BUF) (COBP.GET) (poolid:1) (key:65535) (bufid:9) (count:6) (OraBufReader.GetDataFromNetwork)
> 2020-07-24 15:42:19.625469 TID:9   (PRI) (TUN) (EXT) OracleTuner.DoWait()
> 2020-07-24 15:42:39.632879 TID:9   (PRI) (TUN) OracleTuningAgent::DoScan(): No pools identified for optimization. Stay in SCAN state.
> 2020-07-24 15:42:43.726532 TID:1   (NET) (REC) New receive packet. Header: 

In the version with the literal, I see:

> 2020-07-24 15:44:49.141650 TID:6   (PRI) (TTC) (EXT) TTCExecuteSql.WriteOall8Message()
> 2020-07-24 15:44:49.141659 TID:6   (PRI) (TTC) (EXT) TTCExecuteSql.SendExecuteRequest()
> 2020-07-24 15:44:49.148206 TID:6   (PRI) (TTC) (ENT) TTCExecuteSql.ReceiveExecuteResponse()
> 2020-07-24 15:44:49.148269 TID:6   (NET) (REC) New receive packet. Header: 

It seems that for whatever reason, the provider is entering a waiting state.

I tried the second version with Oracle.EntityFrameworkCore 2.19.80. The logs file is "2.19.80.trc" (see my mail).

Once again, I can see

> 2020-07-24 15:48:58.688789 TID:1   (PRI) (BUF) (COBP.GET) (poolid:1) (key:65535) (bufid:9) (count:6) (OraBufReader.GetDataFromNetwork)
> 2020-07-24 15:49:08.621661 TID:9   (PRI) (TUN) (EXT) OracleTuner.DoWait()

Finally, I tried with the version 3.19.0-beta2 and the performance were catastrophic. The logs file is "3.19.0-beta2.trc" (see my mail).

Note that these tests have been performed with pooling. Deactivating it does not solve the issue (and it is deactivated on prod because of another problem of the library).

**Comment by alexkeh** [comment]
@ssougnez Thanks for the detailed info and analysis. We received your traces. I've created a bug (31667716) to track your issue and find a resolution. My dev team will review and see if we can determine a root cause. If not, we probably will want the schema to reproduce exactly what you are experiencing in house.

The root cause for the other customer's performance problem on the Oracle forum appears to be different. Your issue appears tied to using dates. The other customer's query does not use any dates.

**Comment by ssougnez** [comment]
Let me add something then...
I noticed the issue with literal versus variable by actually using a different query (sorry, I did so many tests that I forgot to mention it).
The query I tested was against the table containing 400.000.000 records and was retrieving records based on a condition with two AND on nvarchar fields.
I don't have the exact query but it was something like "Where(s => s.Niss = "XYZ" && s.Level == "CK")" and I experienced the exact same issue, so I'm not 100% sure that my issue relates specifically to the "Date" fields.
I might be wrong, but it really seems to me that it is related to the number of records contained in the table, a bit as if the query was executed individually against each and every record.
I assume it's not done like that, but this "DoWait" is waiting for something and it seems that the more record there are, the more it's waiting :-)

**Comment by alexkeh** [comment]
This issue is resolved. 

Explanation: If the EF Core model does not accurately indicate which string properties are and are not Unicode, performance can become significantly degraded, including queries undertaking full scans. When the provider scaffolds the model, this problem shouldn't happen. When the mapping is manually created or the scaffolded model is modified, this performance problem may occur.

To avoid the problem, one can either:
- Use scaffolding to generate the entity classes corresponding to the database tables. The correct fluent API for each of the columns in the table will be generated.
- If manually creating the entity classes corresponding to the database tables, then correctly map each string entity property to the correct column type, especially when identifying whether the data type uses Unicode or not.

For example: By default, the .NET String entity type maps to Oracle NVARCHAR2. If the column type in the database is VARCHAR2, then the IsUnicode(false) or HasColumnType(“VARCHAR2”) fluent API should be used to correctly map the string entity property to VARCHAR2 database type.

**Comment by ssougnez** [comment]
Hi, I confirm that the issue is indeed solved.

Very good email support/follow up by the Oracle team 👍 

Thanks a lot

**Comment by alexkeh** [comment]
No problem @ssougnez. Glad we could help.
