### ISSUE TITLE
Version Problem Oracle.EntityFrameworkCore and Microsoft.EntityFrameworkCore.Relational

### ISSUE THREAD

**Issue by wantal** [oracle/dotnet-db-samples#87]
Hi,
I am trying using Microsoft.EntityFrameworkCore.Relational in my project where I have Oracle.EntityFrameworkCore, but I am have some problems with the versions:
![Screen Shot 08-07-20 at 03 53 PM](https://user-images.githubusercontent.com/15447915/89658542-97cadc80-d8c6-11ea-86a9-d507be7c2cd3.PNG)

So, I did the downgrade of the Microsoft.EntityFrameworkCore.Relational and the problem is solved, but in this version I do not have the method ".HasNoKey()" in context and I needed replace the "FromSqlRaw" to "FromSql" in my repositories, differently of samples  https://github.com/oracle/dotnet-db-samples/blob/master/samples/dotnet-core/ef-core/stored-procedure/return-ref-cursor.cs and https://github.com/oracle/dotnet-db-samples/blob/master/samples/dotnet-core/ef-core/keyless-entity-types-views/keyless-entity-types-views.cs respectively.

Versions:
.Net Core 3.1
Oracle.EntityFrameworkCore 2.19.80
Oracle.ManagedDataAccess.Core 2.19.80
[...]

Best Regards.

**Comment by alexkeh** [comment]
As noted in the README, the keyless entity type sample only supports EF Core 3.1, not EF Core 2.x. That's because keyless entity types themselves are only supported starting with Oracle EF Core 3.1.

The comments in the Ref Cursor sample indicate the code line that needs to be modified when using .NET Core 2.x.
`FromSqlRaw("BEGIN GETALLBLOGS(:blogparam); END;", new object[] { allblogs })   // .NET Core 3.x syntax
 //.FromSql("BEGIN GETALLBLOGS(:blogparam); END;", new object[] { allblogs })    // .NET Core 2.x syntax`
