### ISSUE TITLE
Using ODP.Net Core failover with Data Guard

### ISSUE THREAD

**Issue by luboid** [oracle/dotnet-db-samples#95]
Hello,

I'am trying to use failover capability on ODP.Net with DataGuard, database is not in RAC
Here is my alias:

```
INSTAGR =
	(DESCRIPTION=
	   (ADDRESS_LIST=
		 (ADDRESS=(PROTOCOL=tcp)(HOST=InstaGRDB1-T.test.procreditbank.bg)(PORT=1521))
		 (ADDRESS=(PROTOCOL=tcp)(HOST=InstaGRDB2-T.test.procreditbank.bg)(PORT=1521)))
	   (CONNECT_DATA=(SERVICE_NAME=INSTAGR_SB_CON))
	   (RETRY_COUNT=3)
	)
```

when DBA  switch Data Guard to standby node connection starts giving me:

```ORA-01033: ORACLE initialization or shutdown in progress```

it stop trying to connect at first ADDRESS, here is my code with tnsnames.ora, sqlnet.ora and trace

[CONSOLEAPP17.EXE_PID_13628_DATE_2020_08_28_TIME_09_10_09_881576.zip](https://github.com/oracle/dotnet-db-samples/files/5140317/CONSOLEAPP17.EXE_PID_13628_DATE_2020_08_28_TIME_09_10_09_881576.zip)
[ConsoleApp17.zip](https://github.com/oracle/dotnet-db-samples/files/5140318/ConsoleApp17.zip)

**Comment by alexkeh** [comment]
In OracleConfiguration class, there is a [ServiceRelocationConnectionTimeout] (SRCT) property https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/ConfigurationServiceRelocationConnectionTimeout.html#GUID-0D60966B-A3C7-4CA5-A5DE-764BFE147DD9).  This setting will pause any connection attempt for the number of seconds set during a Data Guard switchover. That provides the server time to bring down the primary and bring up the secondary. SRCT overrides existing timeouts so that the end user sees no timeout errors while the switchover occurs.

This property is also available as a .NET config setting, which is available to managed and unmanaged ODP.NET, but not ODP.NET Core. The reason I want to point that out is that [doc section provides a more comprehensive feature description](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/InstallManagedConfig.html#GUID-A9EF5624-1828-46DD-84D1-CC5F40BFB6F5). The link won't take you to the exact property description. Click on the link and search for ServiceRelocationConnectionTimeout.

Hope that helps.

**Comment by luboid** [comment]
Hi,
Error persists after switch over

**Comment by alexkeh** [comment]
Are you using Oracle Fast Connection Failover (FCF) to ensure existing connections in the pool in the primary are removed from the pool upon the switch over?

FCF is enabled by default with ODP.NET as long as you use connection pooling and leave HA Events=true in the connection string. You just need to enable it on the DB server side. If not enabled, those connections to your primary will be left behind in the pool and users will be dispensed those invalid connections.

Sorry, I got a little ahead of myself. Once you have FCF working, the usual next challenge is ensuring users don't get a timeout during the switchover period, which is what SRCT solves.

**Comment by alexkeh** [comment]
I actually blogged about using [ODP.NET Fast Connection Failover](https://medium.com/oracledevs/drain-dead-connections-with-oracle-net-fast-connection-failover-9de5c11ec484) recently.

**Comment by luboid** [comment]
Hi,
At this time I only start and stop the Console App after switchover, because of that I do not think the connection pool is a problem. No connections in invalid state exists when Console App is started.

I'am know about FAN. [Documetation](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/featRAC.html#GUID-3A7979D7-4AD3-4846-ADC8-A141DA089C8A) states that FAN can be used with Data Guard, which is free for use, but we have argued with our DBA about do we need RAC environment or we can use only Grid Infrastructure,  which is free for use without license. What is your opinion?

**Comment by alexkeh** [comment]
It does sound like your problem is orphaned connections after the switchover, which is what FAN was designed to solve.

FAN supports Data Guard, RAC, and Oracle Grid Infrastructure for Standalone Servers (Oracle Restart). The server type you choose really depends on your use case. Oracle Restart is less expensive because it doesn't provide disaster recovery, DB scalability, and has limited failover capabilities.

**Comment by luboid** [comment]
I'm really in wonder where this connection can be orphaned, if we open service request at metalink, can this help to investigate a problem more in dept.

**Comment by alexkeh** [comment]
When I say "orphaned", I mean the connection exists in the pool, but is no longer connected to the DB instance anymore.

FCF was created to solve this exact problem.

**Comment by luboid** [comment]
Console App is started after switchover, there is no way how to exists connection into the pool because it doesn't exist when switchover is in process. You can see how simple is code

```c#
using System;
using Oracle.ManagedDataAccess.Client;

namespace ConsoleApp17
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                OracleConfiguration.TraceFileLocation = @"F:\temp\traces";
                OracleConfiguration.TraceLevel = 7;
                OracleConfiguration.TraceOption = 0;

                using var conn = new OracleConnection(@"Data Source=INSTAGR; User Id=insta_owner;Password=instagr;HA Events=true;Pooling=true");
                conn.Open();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            Console.WriteLine("Hello World!");
            Console.ReadLine();
        }
    }
}
```

**Comment by alexkeh** [comment]
If the switchover is in proces when the connection pool starts up, I can see why you get this error. When the switchover begins, the FAN event is sent to the registered pools. As your pool does not exist yet, there is no message sent to it. When the pool does start up later, it has already missed the FAN message and then tries to connect to the primary as it is shutting down.

It's an unusual case since typically apps don't start up for the first time during a switchover. I'll bring it up with my team. It may be a scenario we can address in a future release.

**Comment by luboid** [comment]
Sorry, it is too complicated to understand. My DBA want to stop App to clear connections to DB before switchover because some times it can't do it properly and process timeout and make mess. But I think it is not unusual in disaster recovery App to be started after or in process of switchover, however.

**Comment by alexkeh** [comment]
Yes, clearing the connections before a switchover is now completely unnecessary with FCF.

Let me see if I can explain. FCF will send a message to the ODP.NET connection pool when an individual resource, such as a node, database, service, or service member is brought down. Upon receiving this message, ODP.NET will clear the pool of connections to that resource. It won't clear the whole pool unless all the resources the pool is connected to has been brought down.

Generally, the app is already running before the switchover. When the switchover occurs, no new connections should see an error because all connections to the downed resource have been removed.

After the switchover completes, an app can be started and there should be no problem connecting to the secondary database.

The only issue that may occur is when the app is started for the first time in the middle of the switchover. That is what it sounds like your DBA wants to do. If he wants to do that, he needs to wait until the switchover completes before restarting the app. Otherwise, you get the ORA-01033 error.

It's easier just to enable FCF and not manually reset the pool.

**Comment by luboid** [comment]
Thank you
