### ISSUE TITLE
Difference on Scaffold (3.1 vs 2.2)

### ISSUE THREAD

**Issue by rafaelpadovezi** [oracle/dotnet-db-samples#96]
I noticed a difference on Scaffolding when using the beta version 3.19.0-beta2 compared to 2.2.6.

The older version generates the HasIndex for the property Id (the primary key)

```csharp
entity.HasIndex(e => e.Id)
    .HasName("PK_TRIAL_CONTRACT")
    .IsUnique();
```

but the new version don't (although generates the HasIndex correctly to the others index.

I wanna know if this is the expected behavior

**Comment by alexkeh** [comment]
What are the fluent APIs generated now for you with the beta 2?

If the primary key column has the HasKey() fluent API generated (or [key] annotation generated), then it is sufficient because primary key columns have implicit indexes created for them. You cannot explicitly create an index for a primary column.
